class UVO_EN_NationalityConfig {
	nationality = "EN";
	factions[] = 
{
				"BLU_CTRG_F",//BLU_CTRG_F (Pacific CTRG, Apex Expansion)
				"BLU_F",//BLU_F (NATO)
				"BLU_T_F",//BLU_T_F (Pacific NATO, Apex Expansion)
				"LIB_US_AIRFORCE",
				"LIB_US_ARMY",// United States Army
				"LIB_US_TANK_TROOPS",
				"rhs_faction_usarmy_d",
				"rhs_faction_usarmy_wd",
				"rhs_faction_usmc_d",
				"rhs_faction_usmc_wd",
				"rhs_faction_socom_marsoc",
				"FP_SOCOM_DEVGRU",// RHS Plus
				"FP_RHSUSAF_RANGER",// RHS Plus
				"FP_RHSUSAF_RANGER_2000s",// RHS Plus
				"FP_SOAR",// RHS Plus
				"FP_PMC_OG_B",// RHS Plus
				"FP_Germany",// RHS Plus
				"SUD_NATO",
				"CUP_B_USMC",
				"CUP_B_US_Army",
				"CUP_B_US_Navy",
				"CUP_B_US",
				"CFP_B_USMC_DES",
				"CUP_B_USMC_DES",
				//"LOP_UN",
				"LOP_PMC",
				"UK3CB_CW_US_B_EARLY",
				"UK3CB_CW_US_B_LATE",
				"ACM_B_CDF",
				/*ORIGIONAL*/
				"US",
				"BLU_W_F",//BLU_W_F (Woodland NATO, Contact Expansion)
				 "fow_usa",
				 "fow_usmc",
				 "CUP_I_PMC_ION",
				 "LIB_US_RANGERS",// US 2nd Ranger Battalion
				 "LIB_NAC",// US North African Corps
				 "LIB_ARR",// USAAF 447th Bombardment Group
				 "fow_usa_p",
				 "mas_ww2_army_US",
				 "mas_ww2_army_US_hd",
				 "mas_wwm_army_US",
				 "mas_wwm_army_US_hd",
				 "CPC_B_NAM_US",//CPC_Factions_CUP - US forces in viet
				 "rhs_faction_socom",
				 "SPE_US_ARMY",
				 "B_VKN",//Viking PMC  Viking PMC Mod - All-In-One
				 "I_Gen",//Legion   Viking PMC Mod - All-In-One
				 "B_Gen",//Taiga     Viking PMC Mod - All-In-One
				 "O_ION_Winter",//VWF_ION    Viking PMC Mod - All-In-One
				 "BLU_CTRG_tna_F",//A3_Aegis
				 "BLU_ION_F",//A3_Aegis
				 "BLU_NATO_lxWS",//USMC     A3_Aegis
				"Opf_IND_P_F",// ATLAS OPFOR cfgMilitia
				"VIOC_O_US",//VIO_Side_Patch_WW2
				"VIOC_B_US",//VIO_Side_Patch_WW2
				"VIOC_I_US",//VIO_Side_Patch_WW2
				"Exile_US",//VIO_Side_Patch_WW2
				"cox_faction_xoc",//COXHOUND Faction Mod
				"cox_faction_xoc90s",//COXHOUND Faction Mod
				"cox_faction_blackmesa",//COXHOUND Faction Mod
				"cox_faction_coxhound",//COXHOUND Faction Mod
				"cox_faction_mercenaries",//COXHOUND Faction Mod
				"I_Halo",//Halo ALiVE				 
				"LIB_101AB",//Burd's Airborne ALIVE Factions
				"LIB_82AB",//Burd's Airborne ALIVE Factions
				"O_HumanSFG",
				"UNSUNG_W_US",
				"B_USArmy",//ISAF ALiVE Faction
				"MU_CTRG_B",//Missing Units - Complete package
				"MU_spefor_B",//Missing Units - Complete package
				"CFP_B_USRANGERS_WDL",
				"CFP_B_USARMY_WDL",
				"CFP_B_USCIA",
				"CFP_B_USMC_DES",
				"CFP_B_USSEALS_WDL",
				"CFP_B_USSEALS_DES",
				"CFP_B_USARMY_1991_DES",
				"CFP_B_USARMY_1991_WDL",
				"CFP_B_USARMY_2003_DES",
				"CFP_B_USARMY_2003_WDL",
				"nato",
				"cfpUsArmy1991",
				"cupIon",
				"cupUsArmy",
				"cupUsmc",
				"ifa3UsArmy",	
				"rhsUsmc",
				"MR",//US MARSOC Marine Raiders [RHS], US MARSOC Marine Raiders [NIA]
				"SEAL",//US Navy SEALS [RHS]
				"CAN",//Canadian Joint Task Force 2 CANSOF [SMA]
				"O_Raiders",//Fallout Factions Project
				"B_NCR",//Fallout Factions Project
				"I_Settler",//Fallout Factions Project
				"PMC",//Private Military Contractors [SMA]
				"BLU_AI",//US 75th Ranger Regiment [SMA]
				"BLU_AI_T",//US 75th Ranger Regiment [SMA]
				"I_USAB",//US Airborne Light Infantry Company 1944 [IFA3]
				"SL",//US Navy SEALS [NIA]
				"SEAL90",//US Navy SEALS 1990's [CUP]
				"SEALD90",//US Navy SEALS 1990's [CUP]
				"CAG",//US CAG-Delta Force [NIA]
				"OPF_BlackOrder_F",//Terrorist Organization Black Order
				"IND_BlackOrder_F",//Terrorist Organization Blac
				"IND_BlackOrder_MP_F",//Terrorist Organization Blac
				"OPF_BlackOrder_MP_F",//Terrorist Organization Blac
				"OPF_BlackOrder_SCI_F",//Terrorist Organization Blac
				"IND_BlackOrder_SCI_F",//Terrorist Organization Blac
				"QCLASS(IND)",//TheseusServices
				"QCLASS(BLU)",//TheseusServices
				"nswdg_aor1",//US Special Operations Command (All in One/RHS) by GrizzlyBear83
				"nswdg_aor2",
				"nswdg_mc",
				"us_army_delta_mct_rhs",
				"us_army_delta_rhs",
				"us_army_rangers_rhs_2006",
				"us_army_rangers_rhs_2010",
				"us_army_rangers_rhs_2014",
				"us_army_rangers_rhs_2018",
				"us_army_rrc_rhs",
				"us_army_sf_mct_rhs",
				"us_army_sf_rhs",
				"us_marsoc_rhs_desert",
				"us_marsoc_rhs_woodland",
				"usaf_24th_sts_rhs",
				"YSA_SGA_USMC_Units",//sg_Wraith_fact
				"UNSUNG_W_USARMY_65",//ALiVE Unsung Factions 
				"UNSUNG_W_USMC_65",//ALiVE Unsung Factions 
				"UNSUNG_W_USMC_69",//ALiVE Unsung Factions 
				"max_civilian",
				"B_TFDCTRG",//[CUP] NATO: CTRG 2020
				"B_NATO",//NATO Revised (Standalone)
				"JK_B_Wolves_PMC_F",//C-47 Skytrain Mega Pack       00
				"B_NorthAtlanticTreatyOrganizationCombatTechnologyResearchGroup",//Arma Factions Reloaded
				"I_NorthAtlanticTreatyOrganizationCombatTechnologyResearchGroup",//Arma Factions Reloaded
				"O_NorthAtlanticTreatyOrganizationCombatTechnologyResearchGroup",//Arma Factions Reloaded
				"mas_usm_aveg",//MASSI’s MOD
				"mas_usm_bdes",//MASSI’s MOD
				"mas_usm_cwint",//MASSI’s MOD
				"mas_usm_dspec",//MASSI’s MOD
				"mas_usm_fonu",//MASSI’s MOD
				"mas_usm_honu",	//MASSI’s MOD	
				"mas_usm_gmars",//MASSI’s MOD
				"mas_nat_actrg",//MASSI’s MOD
				"mas_nat_bctrg_par",//MASSI’s MOD
				"mas_nat_cctrg_div",//MASSI’s MOD
				"mas_nat_dctrg_CBRN",//MASSI’s MOD
				"mas_nat_ectrg_wint",//MASSI’s MOD
				"mas_nat_nctrg_US",//MASSI’s MOD
				"mas_nat_nctrg_CAN",//MASSI’s MOD
				"USA_fow",//Faces of War Side Patch
				"sdk_O_USA",//Faces of War Side Patch				
				"sdk_b_us_army_w",//Nazi German SS Troops - mOD
				"sdk_O_US_Army_w",//Nazi German SS Troops - mOD
				"TFC_A3_TEMPERATE",//Task Force Canada (TFC-CAF)
				"TFC_A3_Arid",//Task Force Canada (TFC-CAF)
				"TFC_A3",//Task Force Canada (TFC-CAF)
				"TFC_A3_MULTI_TERRAIN",//Task Force Canada (TFC-CAF)
				"TFC_A3_WINTER",//Task Force Canada (TFC-CAF)
				"TFC_A3_SOF",//Task Force Canada (TFC-CAF)
				"B_G8",        // "LWF - Group 8";
				"B_G13",       //  "LWF - Group 13";
				"B_USA_A",       //  "LWF - US Army (Arid)";
				"B_USA_W",       //  "LWF - US Army (Woodland)";
				"B_IONS",       //  "LWF - ION Services";
				"Faction_DD_F",//Metal Gear Factions     Diamond Dogs
				"Faction_XOF_F",//Metal Gear Factions
				"UNSUNG_W",	//UNSUNG	   US
				"VW_Faction_USA",//Vietnam Mod (CUP-S&S)
				"VW_Faction_USA_SAS",//Vietnam Mod (CUP-S&S)
				"cwr3_faction_usa",//CWR3
				"cwr3_faction_usa_des",//CWR3
				"B_USGreenBerets_BDU",
				"SIMC_UA_101_07",//US Forces 2000's
				"SIMC_UA_101_07A",//US Forces 2000's
				"SIMC_UA_10MTN_07",//US Forces 2000's
				"SIMC_UA_10MTN_07A",//US Forces 2000's
				"SIMC_UA_173RD_07",
				"SIMC_UA_173RD_07A",
				"SIMC_UA_1cav_07",
				"SIMC_UA_1cav_07a",//US Forces 2000's
				"SIMC_UA_1ID_07",
				"SIMC_UA_1ID_07a",
				"SIMC_UA_2acr_07",//US Forces 2000's
				"SIMC_UA_2acr_07a",
				"SIMC_UA_3ID_07",
				"SIMC_UA_3ID_07A",
				"SIMC_UA_4ID_07",//US Forces 2000's
				"SIMC_UA_4ID_07A",
				"SIMC_UA_101_08",
				"SIMC_UA_101_08A",
				"SIMC_UA_10MTN_08",
				"SIMC_UA_10MTN_08A",
				"SIMC_UA_173RD_08",
				"SIMC_UA_173RD_08A",//US Forces 2000's
				"SIMC_UA_1cav_08",
				"SIMC_UA_1cav_08a",
				"SIMC_UA_1ID_08",
				"SIMC_UA_1ID_08a",
				"SIMC_UA_2acr_08",//US Forces 2000's
				"SIMC_UA_2acr_08a",
				"SIMC_UA_3ID_08",
				"SIMC_UA_3ID_08A",
				"SIMC_UA_4ID_08",
				"SIMC_UA_4ID_08A",
				"SIMC_UA_25_07",//US Forces 2000's
				"SIMC_UA_2ID_07",
				"SIMC_UA_3ID_07",
				"SIMC_UA_101_07",
				"SIMC_UA_25_07_D",
				"SIMC_UA_509_07_D",//US Forces 2000's
				"SIMC_UA_25_07_D",
				"SIMC_UA_3ID_07",
				"SIMC_UA_2ID_07",
				"SIMC_UA_3ID_07",
				"SIMC_UA_502D_07_D",
				"SIMC_UA_101_07_D",
				"SIMC_UA_327TH_07_D",//US Forces 2000's
				"SIMC_UA_187TH_07_D",
				"SIMC_UA_506TH_07_D",
				"SIMC_UA_101_08",
				"SIMC_UA_101_08_D",
				"SIMC_UA_187TH_08_D",
				"SIMC_UA_25_08",	
				"SIMC_UA_25_08_D",
				"SIMC_UA_25_08_D",
				"SIMC_UA_2ID_08",//US Forces 2000's
				"SIMC_UA_2ID_08",
				"SIMC_UA_327TH_08_D",
				"SIMC_UA_3ID_08",
				"SIMC_UA_3ID_08",
				"SIMC_UA_3ID_08",
				"SIMC_UA_4ID_08A",//US Forces 2000's
				"SIMC_UA_502D_08_D",
				"SIMC_UA_506TH_08_D",
				"SIMC_UA_509_08_D",
				"SIMC_MC_04_D",
				"SIMC_MC_04_W",
				"SIMC_MC_05_D",	
				"SIMC_MC_05_W",//US Forces 2000's
				"SIMC_MC_08_D",
				"SIMC_MC_08_W",
				"SIMC_UA_05_D",
				"SIMC_UA_05_W",//US Forces 2000's
				"SIMC_UA_06",//US Forces 2000's
				"SIMC_UA_08",//US Forces 200//US Forces 2000's0's
				"SIMC_UA_07",//US Forces 2000's
				"usm_usarmy",//US Military Mod
				"usm_usmarinecorps",//US Military Mod
				"BLU_USA1980_L",//1980's US-USSR Factions
				"BLU_USA1980_W_L",	//1980's US-USSR Factions
				"BLU_USA1980_E",//1980's US-USSR Factions
				"BLU_USA1980_W_E",//1980's US-USSR Factions
				"B_USArmy",	//Floppy's ArmA 1 US Army Faction
				"RHS_VSM_B_USA",//Big Monke's SFOD-D
				"max_WY_faction",//USCM Mod
				"max_USCM_faction",//USCM Mod
				"vil_aliency",//Vilas Aliens Mod
				"vil_aliency_weyland",//Vilas Aliens Mod
				"USAF",//USAF 2019
				"TNKD_USMC_2022",//USMC 2022
				"EF_UNITS",//ENFORCER
				"EF_OUNITS",//ENFORCER
				"Skynet",//Max_Terminator
				"resistance",//Max_Terminator
				"Pred_Human",	//Max Predator			
				"us_delforce_1993",	//U.S Delta Force 90's
				"us_delforce_1993_w",//U.S Delta Force 90's
				"MCLU_NATO_B",//Arma Rearmed 3
				"aan_tv_2035",//Arma Rearmed 3
				"FUTARM_MT_UNIT",//Arma Rearmed 3
				"nato_2035",//Arma Rearmed 3
				"B_unitedstatesofamericaarmy",//Afghan forgotten war camp
				"JMSSA_canadian_fact",//JM Second Assault ww2
				"JMSSA_canadian_sicily_fact",//JM Second Assault ww2
				"US_Military_Police",//US Military Police WWII 1940-1945
				"Simc_UA_69",//S&S
				"Simc_UA_67",//S&S
				"Simc_MC_67",	
				"Simc_MC_69",
				"Simc_MC_65",//S&S
				"Simc_UA_65",	
				"Simc_MC_81",//S&S
				"Simc_MC_75",
				"Simc_UA_75",//S&S
				"Simc_UA_81",//S&S
				"Simc_UA_65_ETO",//S&S
				"MEOP_human",//JM mass effect opposition
				"MEOP_cerber",//JM mass effect opposition
				"fff_VBORA",//Fight For Freedom!
				"WebNiX_Corp_SpecOps",//E.P.S.M ExoMod Remastered
				"WebNiX_Corp_AssaultGroup",//E.P.S.M ExoMod Remastered
				"RHS_B_",//Big Monke's vanilla factions overhauled 
				"CFP_I_WestUltra",//Western Ultranationalists / Terrorist 
				"I_US_Army",//Western Front Plus	
				"I_USArmy",	//Western Front Plus	
				"I_US_Airborne",//Western Front Plus	
				"I_USAirborne",//Western Front Plus	
				"I_US_Rangers",	//Western Front Plus	
				"I_USRangers",//Western Front Plus				
				 "GEISTUSArmy",
				 "GEISTUSArmored",
				  "GEISTUSAF",
				 "sab_sw_faction_green",//sab Secret Weapons Reloaded
				 "sab_fl_faction_green",//sab Flying Legends
				 "sab_nl_faction_green",//sab Naval Legends
				 "sab_milavi_faction_blue",//sab Military Aviation		
				"MALHAMA",//MILITIA fast factions
				 "USA",
				 "USCG",
				 "delta",
				 "DEVGRU",
				 "JSOC",
				 "socom",
				 "ussocom",
				 "swat",
				 "hrt",
				 "cia",
				 "fbi",
				 "SAD",
				 /* 1st update*/
"B_Canada_wdl",//ADF Canadian Armed Force
"B_USACO",//Coalition 2025   -North American Coalition, its mainly a reworked US Army without the Israelian Tank, (replaced by Burnes Abrams), there will be few SF Subgroup (Canadian, Australian, New Zealand).


"B_usaf_24th_sts_2035",//US Special Operations Command (2035) by GrizzlyBear83 
"B_usarmy_special_forces_2035",
"B_usarmy_special_forces_mct_2035",
"B_usarmydelta_2035",//US Special Operations Command (2035) by GrizzlyBear83 
"B_usarmydelta_mct_2035",
"B_usarmyrangers_2035",
"B_usmarsoc_raiders_2035",//US Special Operations Command (2035) by GrizzlyBear83 
"B_usnavydevgru_aor1_2035",
"B_usnavydevgru_aor2_2035",//US Special Operations Command (2035) by GrizzlyBear83 


"B_UnitedStatesMarines_DES",//2035 United States Marine Corps (USMC)
"B_UnitedStatesMarines_WDL",

"B_USA_1967",//Project Vietnam: Faction Pack [DISCONTINUED]
"B_USA_LRRP_TS",
"B_USA_1SFG",//Project Vietnam: Faction Pack [DISCONTINUED]
"B_USA_SOG",
"B_USA_SOG_OD",//Project Vietnam: Faction Pack [DISCONTINUED]
"B_USN_ST2",

"B_USA_1965",//[S&S] Project: Vietnam Factions Pack
"PVN_USA_1968",
//"B_USA_LRRP_TS",
"PVN_USA_7AC",//[S&S] Project: Vietnam Factions Pack

"B_SS_USM_1965",//[S&S] Project: Vietnam Factions Pack
"PVN_USM_1967",
"PVN_USM_1968",//[S&S] Project: Vietnam Factions Pack

"F_US_ARMY",//IFA3
"F_US_ARMY_W",
"F_US_RANGERS",
"F_US_101AB",

"OFG_D_UNITS_NAC",//OFG Unit Loadouts
"OFG_C_UNITS_NAC",
"OFG_L_UNITS_NAC",
"OFG_RP_UNITS_NAC",//OFG Unit Loadouts

"MR",
"BLU_AI",


/*---------24-5-12---------------*/	

"simc_uaf_81",//S & S: New Wave
"simc_uaf_88",
"simc_uaf_88",
"simc_uaf_93",//S & S: New Wave

"FEDERATION",//Gamenator's Custom Factions	Federation Infantry
"SICARIO",//Gamenator's Custom Factions

"SURVIVOR_blue_Faction",//Ravage
"SURVIVOR_green_Faction",//Ravage
"SURVIVOR_red_Faction",//Ravage

"Ravage",//Ravage
"RENEGADE_Faction",//Ravage
"RAIDER_green_Faction",//Ravage
"RAIDER_red_Faction",//Ravage
"RAIDER_blue_Faction",//Ravage	

"us85",//

"USCM",
"Ex3B_BLU_F",
"UnitedNationsSpacy",
"U_N_SPACY_BLU",
"U_N_SPACY",
"KA_Land_Warrior",
"b_custommeleenpcblufor",
"WBK_AI_Melee",
"EMP_Greystone_PMC",
"sga_fun_stuff",//shopping cart
"I_USPMC",//         "[CORP] Security Agents";		[CORP] More Vanilla Factions

"3CB_US80_WDL",//DUWS_X FACTIONS
"BLU_F_ARID",
"BLU_F_PACIFIC",
"CUP_B_USArmy_OCP_Desert",
"CUP_B_USArmy_OCP_Woodland",
"CUP_B_US_Army_D",
"CUP_B_US_Army_W",
"CUP_B_USMC_D",
"CUP_B_USMC_W",
"CWR3_B",//CWR3 US Armed Forces (1985)
"CWR3_USA",
"NATO_WINTER",
"RHS_faction_USAIRBORNE_D",
"RHS_faction_USAIRBORNE_OCP_D",
"RHS_faction_USAIRBORNE_WD",
"RHS_faction_USAIRBORNE_OCP_WD",
"RHS_faction_USAIRBORNE_UCP_D",
"RHS_faction_USAIRBORNE_UCP_WD",
"RHS_faction_USARMY_OCP_D",
"RHS_faction_USARMY_OCP_WD",
"RHS_faction_USARMY_UCP_WD",
"RHSUSF_USMC",
"RHSUSF_USMC_D",
"RHSUSF_USMC_WD",
"TFC",//Task Force Canada
"TFC_TEMP",
"B_MACV",
"DLC_US_ARMY_MACVSOG",
"DLC_US_ARMY_MIKEFORCE",
"UNSUNG_1ID_65",
"UNSUNG_25ID_68",
"UNSUNG_25ID_LRRPS_68",
"UNSUNG_W_USMC",
"UNSUNG_US_MARINES_65",
"UNSUNG_US_MARINES_68",
"UNSUNG_US_MARINES_LRRPS_65",
"UNSUNG_US_MARINES_RECON_68",
"UNSUNG_US_MARINES_SEALS_65",
"FOW_IFA_82ndAIRBORNE",
"FOW_IFA_101stAIRBORNE",
"FOW_IFA_US_MARINES",
"LIB_US_82AB",
"IFA_82ndAIRBORNE",
"LIB_US_101AB",
"IFA_101stAIRBORNE",
"IFA_US_ARMY",
"IFA_US_ARMY_DESERT",
"LIB_US_ARMY_w",
"IFA_US_ARMY_WINTER",
"Simc_UA_ETO",//US GEN EQUIP & ACC IFA US ARMY (Europe)
"USGEA_US_ARMY",
"Simc_UA_ETO_w",
"USGEA_US_ARMY_WINTER",


/*--------24-9-3--------------*/	
				"LM_UNSC_Army",//OPCAN 3.0
				"LM_OPCAN_UNSC_Army_D",
				"LM_OPCAN_UNSC_Army_MIX",
				"LM_OPCAN_UNSC_MC",//OPCAN 3.0
				"LM_OPCAN_UNSC_MC_CEA",
				"LM_OPCAN_UNSC_MC_D",
				"LM_OPCAN_UNSC_MC_INF",//OPCAN 3.0
				"TCF_UNSC",
				"I_ColMA_OPTRE",//Colonial Military Authority ALiVE Faction 1.0 [Standalone]
				"OPTRE_UNSCDF_ALIVE",//OPTRE - ALiVE Faction Compatibility Patch (Outdated)
				"B_UNMar_OPTRE",//UNSCDF ALiVE Faction 1.0 [Standalone]
				"OPTRE_UNSC",//OPTRE
				"OPTRE_PD",
"OFE_DES_A_UNSC_Army",// OPTRE Faction Extension (OFE) - (UNSC Army Desert)
"OFE_WDL_A_UNSC_Army",//- (UNSC Army Woodland)
"OFE_CEA_M_UNSC_Marines",//- (UNSC Marine Corps CE: Anniversary)
"OFE_DES_M_UNSC_Marines",//- (UNSC Marine Corps Desert)
"OFE_WDL_M_UNSC_Marines",//OPTRE Faction Extension (OFE) - (UNSC Marine Corps Woodland)
"OFE_RCH_M_UNSC_Marines",//- (UNSC Marine Corps Reach Camo)
"OFE_DES_C_Colonial_Guard_Corps",// - (Colonial Guard Corps Guard Desert)
"OFE_WDL_C_Colonial_Guard_Corps",// - (Colonial Guard Corps Woodland)
"OFE_DES_C_Colonial_Militia",//OPTRE Faction Extension (OFE)  - (Colonial Militia Desert)
"OFE_WDL_C_Colonial_Militia",//- (Colonial Militia Woodland)

"OFE_CMA_C_Colonial_Military_Authority",//OPTRE Faction Extension (OFE)  – (Colonial Military Authority)

"OPCANEX_UNSCAR_DES_OPCANEX_UNSC_Army_DES",//OPTRE OPCAN Factions Extension - (UNSC Army Desert)
"OPCANEX_UNSCAR_WDL_OPCANEX_UNSC_Army_WDL",//OPTRE OPCAN Factions Extension- (UNSC Army Woodland)
"OPCANEX_UNSCMC_CEA_OPCANEX_UNSC_Marines_Corps_CEA",//OPTRE OPCAN Factions Extension - (UNSC Marine Corps CE: Anniversary)
"OPCANEX_UNSCMC_DES_OPCANEX_UNSC_Marines_Corps_DES",//OPTRE OPCAN Factions Extension- (UNSC Marine Corps Desert)
"OPCANEX_UNSCMC_WDL_OPCANEX_UNSC_Marines_Corps_WDL",//OPTRE OPCAN Factions Extension- (UNSC Marine Corps Woodland)
"OPCANEX_CGC_DES_OPCANEX_Colonial_Guard_Corps_DES",//OPTRE OPCAN Factions Extension - (Colonial Guard Corps Desert)
"OPCANEX_CGC_WDL_OPCANEX_Colonial_Guard_Corps_WDL",//OPTRE OPCAN Factions Extension- (Colonial Guard Corps Woodland)

"OPCANEX_CMA_OPCANEX_Colonial_Military_Authority",//OPTRE OPCAN Factions Extension - (Colonial Military Authority)	
"OPTRE_UNSC_OLI",//DUWS_X FACTIONS
"OPTRE_UNSC_WDL",

"B_UNSCAF",

"TEI_UNSC",//The Eridanus Insurection	UNSCDF: TEI_UNSC

		"OPTRE_Ins",
		"LM_OPCAN_CPD",//OPCAN 3.0
		"LM_OPCAN_CGC",
		"LM_OPCAN_CGC_WDL",
		"LM_OPCAN_CMA",//OPCAN 3.0
		"TCF_Insurrectionist",
		"TCF_Neutral",
		"TCF_Civillian",

"OFE_DES_SG_Sedran_Guard",// - (Sedran Guard Desert)
"OFE_WDL_SG_Sedran_Guard",//OPTRE Faction Extension (OFE)  - (Sedran Guard Woodland)
"OFE_V_VPM_Venezian_Plantary_Militia",// – (Venezian Plantary Militia)
			
"OFE_SEC_SU",//OPTRE Faction Extension (OFE)  - (Secessionist Union)
			
"OFE_WDL_U_United_Rebel_Army",//OPTRE Faction Extension (OFE)  - (United Rebel Army Woodland)
"OFE_DES_U_United_Rebel_Army",// - (United Rebel Army Desert)
				"C_ColCiv_OPTRE",//Civilian ALiVE Faction 1.0 [Standalone]
			
"OPCANEX_URF_WDL_OPCANEX_United_Rebel_Army_WDL",//OPTRE OPCAN Factions Extension - (United Rebel Army Woodland)
"OPCANEX_URF_DES_OPCANEX_United_Rebel_Army_DES",//OPTRE OPCAN Factions Extension - (United Rebel Army Desert)
"OPCANEX_SEC_OPCANEX_Secessionist_Union",//OPTRE OPCAN Factions Extension - (Secessionist Union)
"OPCANEX_Friedens_WDL_OPCANEX_Friedens_WDL",//OPTRE OPCAN Factions Extension - (Friedens Woodland)
"OPCANEX_Friedens_GRY_OPCANEX_Friedens_GRY",//OPTRE OPCAN Factions Extension - (Friedens Gray)
"OPCANEX_Friedens_DES_OPCANEX_Friedens_DES",//OPTRE OPCAN Factions Extension - (Friedens Desert)

"OPTRE_COVNT",
"OPTRE_UNSC_MAR",
		"O_ColURF_OPTRE",//United Rebel Front ALiVE Faction 1.0 [Standalone]
		"OPTRE_INS_ALIVE",//OPTRE - ALiVE Faction Compatibility Patch (Outdated)
		"O_ColIns_OPTRE",//Insurrection ALiVE Faction 1.0 [Standalone]
"OPTRE_CAA",
"OPTRE_UEG_Civ",
"OPTRE_DME",
"TEI_Ins",//The Eridanus Insurection	Insurrectionists: TEI_Ins


"TAZ_MACV_CUSTOM",//Tazman_CZ's SOG factions
"B_NATO_CUP1",// my custom
"LIB_US_TANK_TROOPS",	//ifa3
"CAF_TW",//Canadian Armed Forces
"CAF_AR",
"mas_usa_mars",//US Marine Corp and MARSOC units
"mas_usa_delta",//USSOCOM 75th Ranger and Navy SEALs DEVGRU
"mas_usa_devg",
"mas_usa_rang",
"mas_usa_usoc",
"sab_air_faction_ssw_1_af",//US
"sab_air_faction_ssw_1",
"Cobra_USARMY",//Cobra's Alive Factions for Unsung Vietnam Mod
"RHS_US_Army_Arid",//A3-Antistasi-Ultimate   https://github.com/SilenceIsFatto/A3-Antistasi-Ultimate/blob/stable/A3A/addons/core/Templates/Templates.hpp
"RHS_US_Army_Temperate",
"RHS_USMC_Arid",
"RHS_USMC_Temperate",
"Simc_US_101AB",//US GEAr: Units (IFA3)
"Simc_US_101AB_Late",
"Simc_US_17AB",
"Simc_US_82AB",
"Simc_US_82AB_Early",
"Simc_US_82AB_Late",
"Simc_UA_Erla",
"Simc_UA_43",
"Simc_UA_ETO",
"Simc_UA_ETO_w",
"Simc_UA_44",
"Simc_UA_NAC",
"Simc_UA_PTO",
"Simc_UA_PTO_late",
"Simc_USN",
"Simc_USMC_44",
"Simc_USMC_42",
"Simc_USMC_Green",
"Simc_USMC_45",
"Simc_USMC_sand",

/*----------------24-9-16---------------------------------------------*/	
"UAG",//UAG Units
"sia_faction_cia",//CIA  //SIA Additional Factions V2 (DEV)
"OAF_Core_Oasean_Armed_Forces",//Oasean Armed Forces 2041 [ALPHA]

"USA_Faction",//Cold War Factions
"B_USMarines",//HECU//CUP HECU [FACTION]
"O_USMarines",
"Floppy_A1_USA",//US Army 1990s//Floppy local
"Floppy_A2OA_USA",

/*-----------------------------25-1-7--------------------*/	
"cwr3_faction_usmc",

"FP_PMC_OG_B",//RHS plus			Murkywater PMC: FP_PMC_OG_B
"FP_PMC_OG_R",//RHS plus	Murkywater PMC (OPFOR): FP_PMC_OG_R
"FP_PMC_OG_G",//RHS plus	Murkywater PMC Independent: FP_PMC_OG_G

"B_AEF_EARLY",//44Factions[WWR]        displayName = "American Expeditionary Forces";
"B_AEF_LATE",//44Factions[WWR]        displayName = "American Expeditionary Forces (Late)";
"B_HARH",//44Factions[WWR]        displayName = "Harlem Hellfighters"; USA

"TTU_FE_Fac_CTRG_ARD",//TTU Factions Expanded					displayName = [FE] Combat Tech Research Group (Arid c.2035);
"TTU_FE_Fac_CTRG_TRP",//TTU Factions Expanded				displayName = [FE] Combat Tech Research Group (Tropical c.2035);
"TTU_FE_Fac_USA_MTP",//TTU Factions Expanded				displayName = [FE] US Army (MTP c.2035);
"TTU_FE_Fac_USA_TRP",//TTU Factions Expanded					displayName = [FE] US Army (Tropical c.2035);
"TTU_FE_Fac_USA_WDL",//TTU Factions Expanded					displayName = [FE] US Army (Woodland c.2035);
"TTU_FE_Fac_USASOC_MTP",//TTU Factions Expanded					displayName = [FE] US Army Spec Ops (MTP c.2035);
"TTU_FE_Fac_USASOC_TRP",//TTU Factions Expanded					displayName = [FE] US Army Spec Ops (Tropical c.2035);
"TTU_FE_Fac_USASOC_WDL",//TTU Factions Expanded				displayName = [FE] US Army Spec Ops (Woodland c.2035);

"O_USSealVBSS",	//        displayName = "[VBSS] Seal Team 3";

"PRACS_IMAS",//        displayName="International Military Assistance, Sahrani";        icon="\a3\Data_f\Flags\flag_nato_co.paa";

"BLU_ION_lxWS",//TTU Factions Expanded Western Sahara		
"TTU_FE_lxWS_Fac_ION",//TTU Factions Expanded Western Sahara				displayName = [FE lxWS] ION Services (c.2035);
"TTU_FE_lxWS_Fac_USA_DST",//TTU Factions Expanded Western Sahara				displayName = [FE lxWS] US Army (Desert c.2035);
"TTU_FE_lxWS_Fac_USASOC_DST",//TTU Factions Expanded Western Sahara				displayName = [FE lxWS] US Army Spec Ops (Desert c.2035);

"SAD",	//EricJ Taliban Fighters     cia sad
	
/*-------------------------end-lines------------------------------------*/	
				 "B_USArmy85_WD"//Cold War Rearmed 3 Faction Configs
};	
	
	class events {
		calloutsN[] = {
			"EN_call_spottednorth01",
			"EN_call_spottednorth02",
			"EN_call_spottednorth03",
			"EN_call_spottednorth04",
			"EN_call_spottednorth05",
			"EN_call_spottednorth06",
			"EN_call_spottednorth07",
			"EN_call_spottednorth08",
			"EN_call_spottednorth09",
			"EN_call_spottednorth10",
			"EN_call_spottednorth11",
			"EN_call_spottednorth12",
			"EN_call_spottednorth13",
			"EN_call_spottednorth14",
			"EN_call_spottednorth15",
			"EN_call_spottednorth16",
			"EN_call_spottednorth17",
			"EN_call_spottednorth18",
			"EN_call_spottednorth19",
			"EN_call_spottednorth20",
			"EN_call_spottednorth21",
			"EN_call_spottednorth22",
			"EN_call_spottednorth23",
			"EN_call_spottednorth24",
			"EN_call_spottednorth25",
			"EN_call_spottednorth26",
			"EN_call_spottednorth27",
			"EN_call_spottednorth28",
			"EN_call_spottednorth29",
			"EN_call_spottednorth30",
			"EN_call_spottednorth31",
			"EN_call_spottednorth32",
			"EN_call_spottednorth33",
			"EN_call_spottednorth34",
			"EN_call_spottednorth35",
			"EN_call_spottednorth36",
			"EN_call_spottednorth37",
			"EN_call_spottednorth38",
			"EN_call_spottednorth39",
			"EN_call_spottednorth40",
			"EN_call_spottednorth41",
			"EN_call_spottednorth42",
			"EN_call_spottednorth43",
			"EN_call_spottednorth44",
			"EN_call_spottednorth45",
			"EN_call_spottednorth46",
			"EN_call_spottednorth47",
			"EN_call_spottednorth48",
			"EN_call_spottednorth49",
			"EN_call_spottednorth50",
			"EN_call_spottednorth51",
			"EN_call_spottednorth52",
			"EN_call_spottednorth53",
			"EN_call_spottednorth54",
			"EN_call_spottednorth55",
			"EN_call_spottednorth56",
			"EN_call_spottednorth57",
			"EN_call_spottednorth58",
			"EN_call_spottednorth59",
			"EN_call_spottednorth60",
			"EN_call_spottednorth61",
			"EN_call_spottednorth62",
			"EN_call_spottednorth63",
			"EN_call_spottednorth64",
			"EN_call_spottednorth65",
			"EN_call_spottednorth66",
			"EN_call_spottednorth67",
			"EN_call_spottednorth68",
			"EN_call_spottednorth69",
			"EN_call_spottednorth70",
			"EN_call_spottednorth71",
			"EN_call_spottednorth72",
			"EN_call_spottednorth73",
			"EN_call_spottednorth74",
			"EN_call_spottednorth75",
			"EN_call_spottednorth76",
			"EN_call_spottednorth77",
			"EN_call_spottednorth78",
			"EN_call_spottednorth79",
			"EN_call_spottednorth80",
			"EN_call_spottednorth81",
			"EN_call_spottednorth82",
			"EN_call_spottednorth83",
			"EN_call_spottednorth84",
			"EN_call_spottednorth85",
			"EN_call_spottednorth86",
			"EN_call_spottednorth87",
			"EN_call_spottednorth88",
			"EN_call_spottednorth89",
			"EN_call_spottednorth90",
			"EN_call_spottednorth91",
			"EN_call_spottednorth92",
			"EN_call_spottednorth93",
			"EN_call_spottednorth94",
			"EN_call_spottednorth95",
			"EN_call_spottednorth96",
			"EN_call_spottednorth97",
			"EN_call_spottednorth98",
			"EN_call_spottednorth99",
			"EN_call_spottednorth100"
		};
		calloutsNE[] = {
			"EN_call_spottednortheast01",
			"EN_call_spottednortheast02",
			"EN_call_spottednortheast03",
			"EN_call_spottednortheast04",
			"EN_call_spottednortheast05",
			"EN_call_spottednortheast06",
			"EN_call_spottednortheast07",
			"EN_call_spottednortheast08",
			"EN_call_spottednortheast09",
			"EN_call_spottednortheast10",
			"EN_call_spottednortheast11",
			"EN_call_spottednortheast12",
			"EN_call_spottednortheast13",
			"EN_call_spottednortheast14",
			"EN_call_spottednortheast15",
			"EN_call_spottednortheast16",
			"EN_call_spottednortheast17",
			"EN_call_spottednortheast18",
			"EN_call_spottednortheast19",
			"EN_call_spottednortheast20",
			"EN_call_spottednortheast21",
			"EN_call_spottednortheast22",
			"EN_call_spottednortheast23",
			"EN_call_spottednortheast24",
			"EN_call_spottednortheast25",
			"EN_call_spottednortheast26",
			"EN_call_spottednortheast27",
			"EN_call_spottednortheast28",
			"EN_call_spottednortheast29",
			"EN_call_spottednortheast30",
			"EN_call_spottednortheast31",
			"EN_call_spottednortheast32",
			"EN_call_spottednortheast33",
			"EN_call_spottednortheast34",
			"EN_call_spottednortheast35",
			"EN_call_spottednortheast36",
			"EN_call_spottednortheast37",
			"EN_call_spottednortheast38",
			"EN_call_spottednortheast39",
			"EN_call_spottednortheast40",
			"EN_call_spottednortheast41",
			"EN_call_spottednortheast42",
			"EN_call_spottednortheast43",
			"EN_call_spottednortheast44",
			"EN_call_spottednortheast45",
			"EN_call_spottednortheast46",
			"EN_call_spottednortheast47",
			"EN_call_spottednortheast48",
			"EN_call_spottednortheast49",
			"EN_call_spottednortheast50",
			"EN_call_spottednortheast51",
			"EN_call_spottednortheast52",
			"EN_call_spottednortheast53",
			"EN_call_spottednortheast54",
			"EN_call_spottednortheast55",
			"EN_call_spottednortheast56",
			"EN_call_spottednortheast57",
			"EN_call_spottednortheast58",
			"EN_call_spottednortheast59",
			"EN_call_spottednortheast60",
			"EN_call_spottednortheast61",
			"EN_call_spottednortheast62",
			"EN_call_spottednortheast63",
			"EN_call_spottednortheast64",
			"EN_call_spottednortheast65",
			"EN_call_spottednortheast66",
			"EN_call_spottednortheast67",
			"EN_call_spottednortheast68",
			"EN_call_spottednortheast69",
			"EN_call_spottednortheast70",
			"EN_call_spottednortheast71",
			"EN_call_spottednortheast72",
			"EN_call_spottednortheast73",
			"EN_call_spottednortheast74",
			"EN_call_spottednortheast75",
			"EN_call_spottednortheast76",
			"EN_call_spottednortheast77",
			"EN_call_spottednortheast78",
			"EN_call_spottednortheast79",
			"EN_call_spottednortheast80",
			"EN_call_spottednortheast81",
			"EN_call_spottednortheast82",
			"EN_call_spottednortheast83",
			"EN_call_spottednortheast84",
			"EN_call_spottednortheast85",
			"EN_call_spottednortheast86",
			"EN_call_spottednortheast87",
			"EN_call_spottednortheast88",
			"EN_call_spottednortheast89",
			"EN_call_spottednortheast90",
			"EN_call_spottednortheast91",
			"EN_call_spottednortheast92",
			"EN_call_spottednortheast93",
			"EN_call_spottednortheast94",
			"EN_call_spottednortheast95",
			"EN_call_spottednortheast96",
			"EN_call_spottednortheast97",
			"EN_call_spottednortheast98",
			"EN_call_spottednortheast99",
			"EN_call_spottednortheast100"
		};
		calloutsE[] = {
			"EN_call_spottedeast01",
			"EN_call_spottedeast02",
			"EN_call_spottedeast03",
			"EN_call_spottedeast04",
			"EN_call_spottedeast05",
			"EN_call_spottedeast06",
			"EN_call_spottedeast07",
			"EN_call_spottedeast08",
			"EN_call_spottedeast09",
			"EN_call_spottedeast10",
			"EN_call_spottedeast11",
			"EN_call_spottedeast12",
			"EN_call_spottedeast13",
			"EN_call_spottedeast14",
			"EN_call_spottedeast15",
			"EN_call_spottedeast16",
			"EN_call_spottedeast17",
			"EN_call_spottedeast18",
			"EN_call_spottedeast19",
			"EN_call_spottedeast20",
			"EN_call_spottedeast21",
			"EN_call_spottedeast22",
			"EN_call_spottedeast23",
			"EN_call_spottedeast24",
			"EN_call_spottedeast25",
			"EN_call_spottedeast26",
			"EN_call_spottedeast27",
			"EN_call_spottedeast28",
			"EN_call_spottedeast29",
			"EN_call_spottedeast30",
			"EN_call_spottedeast31",
			"EN_call_spottedeast32",
			"EN_call_spottedeast33",
			"EN_call_spottedeast34",
			"EN_call_spottedeast35",
			"EN_call_spottedeast36",
			"EN_call_spottedeast37",
			"EN_call_spottedeast38",
			"EN_call_spottedeast39",
			"EN_call_spottedeast40",
			"EN_call_spottedeast41",
			"EN_call_spottedeast42",
			"EN_call_spottedeast43",
			"EN_call_spottedeast44",
			"EN_call_spottedeast45",
			"EN_call_spottedeast46",
			"EN_call_spottedeast47",
			"EN_call_spottedeast48",
			"EN_call_spottedeast49",
			"EN_call_spottedeast50",
			"EN_call_spottedeast51",
			"EN_call_spottedeast52",
			"EN_call_spottedeast53",
			"EN_call_spottedeast54",
			"EN_call_spottedeast55",
			"EN_call_spottedeast56",
			"EN_call_spottedeast57",
			"EN_call_spottedeast58",
			"EN_call_spottedeast59",
			"EN_call_spottedeast60",
			"EN_call_spottedeast61",
			"EN_call_spottedeast62",
			"EN_call_spottedeast63",
			"EN_call_spottedeast64",
			"EN_call_spottedeast65",
			"EN_call_spottedeast66",
			"EN_call_spottedeast67",
			"EN_call_spottedeast68",
			"EN_call_spottedeast69",
			"EN_call_spottedeast70",
			"EN_call_spottedeast71",
			"EN_call_spottedeast72",
			"EN_call_spottedeast73",
			"EN_call_spottedeast74",
			"EN_call_spottedeast75",
			"EN_call_spottedeast76",
			"EN_call_spottedeast77",
			"EN_call_spottedeast78",
			"EN_call_spottedeast79",
			"EN_call_spottedeast80",
			"EN_call_spottedeast81",
			"EN_call_spottedeast82",
			"EN_call_spottedeast83",
			"EN_call_spottedeast84",
			"EN_call_spottedeast85",
			"EN_call_spottedeast86",
			"EN_call_spottedeast87",
			"EN_call_spottedeast88",
			"EN_call_spottedeast89",
			"EN_call_spottedeast90",
			"EN_call_spottedeast91",
			"EN_call_spottedeast92",
			"EN_call_spottedeast93",
			"EN_call_spottedeast94",
			"EN_call_spottedeast95",
			"EN_call_spottedeast96",
			"EN_call_spottedeast97",
			"EN_call_spottedeast98",
			"EN_call_spottedeast99",
			"EN_call_spottedeast100"
		};
		calloutsSE[] = {
			"EN_call_spottedsoutheast01",
			"EN_call_spottedsoutheast02",
			"EN_call_spottedsoutheast03",
			"EN_call_spottedsoutheast04",
			"EN_call_spottedsoutheast05",
			"EN_call_spottedsoutheast06",
			"EN_call_spottedsoutheast07",
			"EN_call_spottedsoutheast08",
			"EN_call_spottedsoutheast09",
			"EN_call_spottedsoutheast10",
			"EN_call_spottedsoutheast11",
			"EN_call_spottedsoutheast12",
			"EN_call_spottedsoutheast13",
			"EN_call_spottedsoutheast14",
			"EN_call_spottedsoutheast15",
			"EN_call_spottedsoutheast16",
			"EN_call_spottedsoutheast17",
			"EN_call_spottedsoutheast18",
			"EN_call_spottedsoutheast19",
			"EN_call_spottedsoutheast20",
			"EN_call_spottedsoutheast21",
			"EN_call_spottedsoutheast22",
			"EN_call_spottedsoutheast23",
			"EN_call_spottedsoutheast24",
			"EN_call_spottedsoutheast25",
			"EN_call_spottedsoutheast26",
			"EN_call_spottedsoutheast27",
			"EN_call_spottedsoutheast28",
			"EN_call_spottedsoutheast29",
			"EN_call_spottedsoutheast30",
			"EN_call_spottedsoutheast31",
			"EN_call_spottedsoutheast32",
			"EN_call_spottedsoutheast33",
			"EN_call_spottedsoutheast34",
			"EN_call_spottedsoutheast35",
			"EN_call_spottedsoutheast36",
			"EN_call_spottedsoutheast37",
			"EN_call_spottedsoutheast38",
			"EN_call_spottedsoutheast39",
			"EN_call_spottedsoutheast40",
			"EN_call_spottedsoutheast41",
			"EN_call_spottedsoutheast42",
			"EN_call_spottedsoutheast43",
			"EN_call_spottedsoutheast44",
			"EN_call_spottedsoutheast45",
			"EN_call_spottedsoutheast46",
			"EN_call_spottedsoutheast47",
			"EN_call_spottedsoutheast48",
			"EN_call_spottedsoutheast49",
			"EN_call_spottedsoutheast50",
			"EN_call_spottedsoutheast51",
			"EN_call_spottedsoutheast52",
			"EN_call_spottedsoutheast53",
			"EN_call_spottedsoutheast54",
			"EN_call_spottedsoutheast55",
			"EN_call_spottedsoutheast56",
			"EN_call_spottedsoutheast57",
			"EN_call_spottedsoutheast58",
			"EN_call_spottedsoutheast59",
			"EN_call_spottedsoutheast60",
			"EN_call_spottedsoutheast61",
			"EN_call_spottedsoutheast62",
			"EN_call_spottedsoutheast63",
			"EN_call_spottedsoutheast64",
			"EN_call_spottedsoutheast65",
			"EN_call_spottedsoutheast66",
			"EN_call_spottedsoutheast67",
			"EN_call_spottedsoutheast68",
			"EN_call_spottedsoutheast69",
			"EN_call_spottedsoutheast70",
			"EN_call_spottedsoutheast71",
			"EN_call_spottedsoutheast72",
			"EN_call_spottedsoutheast73",
			"EN_call_spottedsoutheast74",
			"EN_call_spottedsoutheast75",
			"EN_call_spottedsoutheast76",
			"EN_call_spottedsoutheast77",
			"EN_call_spottedsoutheast78",
			"EN_call_spottedsoutheast79",
			"EN_call_spottedsoutheast80",
			"EN_call_spottedsoutheast81",
			"EN_call_spottedsoutheast82",
			"EN_call_spottedsoutheast83",
			"EN_call_spottedsoutheast84",
			"EN_call_spottedsoutheast85",
			"EN_call_spottedsoutheast86",
			"EN_call_spottedsoutheast87",
			"EN_call_spottedsoutheast88",
			"EN_call_spottedsoutheast89",
			"EN_call_spottedsoutheast90",
			"EN_call_spottedsoutheast91",
			"EN_call_spottedsoutheast92",
			"EN_call_spottedsoutheast93",
			"EN_call_spottedsoutheast94",
			"EN_call_spottedsoutheast95",
			"EN_call_spottedsoutheast96",
			"EN_call_spottedsoutheast97",
			"EN_call_spottedsoutheast98",
			"EN_call_spottedsoutheast99",
			"EN_call_spottedsoutheast100"
		};
		calloutsS[] = {
			"EN_call_spottedsouth01",
			"EN_call_spottedsouth02",
			"EN_call_spottedsouth03",
			"EN_call_spottedsouth04",
			"EN_call_spottedsouth05",
			"EN_call_spottedsouth06",
			"EN_call_spottedsouth07",
			"EN_call_spottedsouth08",
			"EN_call_spottedsouth09",
			"EN_call_spottedsouth10",
			"EN_call_spottedsouth11",
			"EN_call_spottedsouth12",
			"EN_call_spottedsouth13",
			"EN_call_spottedsouth14",
			"EN_call_spottedsouth15",
			"EN_call_spottedsouth16",
			"EN_call_spottedsouth17",
			"EN_call_spottedsouth18",
			"EN_call_spottedsouth19",
			"EN_call_spottedsouth20",
			"EN_call_spottedsouth21",
			"EN_call_spottedsouth22",
			"EN_call_spottedsouth23",
			"EN_call_spottedsouth24",
			"EN_call_spottedsouth25",
			"EN_call_spottedsouth26",
			"EN_call_spottedsouth27",
			"EN_call_spottedsouth28",
			"EN_call_spottedsouth29",
			"EN_call_spottedsouth30",
			"EN_call_spottedsouth31",
			"EN_call_spottedsouth32",
			"EN_call_spottedsouth33",
			"EN_call_spottedsouth34",
			"EN_call_spottedsouth35",
			"EN_call_spottedsouth36",
			"EN_call_spottedsouth37",
			"EN_call_spottedsouth38",
			"EN_call_spottedsouth39",
			"EN_call_spottedsouth40",
			"EN_call_spottedsouth41",
			"EN_call_spottedsouth42",
			"EN_call_spottedsouth43",
			"EN_call_spottedsouth44",
			"EN_call_spottedsouth45",
			"EN_call_spottedsouth46",
			"EN_call_spottedsouth47",
			"EN_call_spottedsouth48",
			"EN_call_spottedsouth49",
			"EN_call_spottedsouth50",
			"EN_call_spottedsouth51",
			"EN_call_spottedsouth52",
			"EN_call_spottedsouth53",
			"EN_call_spottedsouth54",
			"EN_call_spottedsouth55",
			"EN_call_spottedsouth56",
			"EN_call_spottedsouth57",
			"EN_call_spottedsouth58",
			"EN_call_spottedsouth59",
			"EN_call_spottedsouth60",
			"EN_call_spottedsouth61",
			"EN_call_spottedsouth62",
			"EN_call_spottedsouth63",
			"EN_call_spottedsouth64",
			"EN_call_spottedsouth65",
			"EN_call_spottedsouth66",
			"EN_call_spottedsouth67",
			"EN_call_spottedsouth68",
			"EN_call_spottedsouth69",
			"EN_call_spottedsouth70",
			"EN_call_spottedsouth71",
			"EN_call_spottedsouth72",
			"EN_call_spottedsouth73",
			"EN_call_spottedsouth74",
			"EN_call_spottedsouth75",
			"EN_call_spottedsouth76",
			"EN_call_spottedsouth77",
			"EN_call_spottedsouth78",
			"EN_call_spottedsouth79",
			"EN_call_spottedsouth80",
			"EN_call_spottedsouth81",
			"EN_call_spottedsouth82",
			"EN_call_spottedsouth83",
			"EN_call_spottedsouth84",
			"EN_call_spottedsouth85",
			"EN_call_spottedsouth86",
			"EN_call_spottedsouth87",
			"EN_call_spottedsouth88",
			"EN_call_spottedsouth89",
			"EN_call_spottedsouth90",
			"EN_call_spottedsouth91",
			"EN_call_spottedsouth92",
			"EN_call_spottedsouth93",
			"EN_call_spottedsouth94",
			"EN_call_spottedsouth95",
			"EN_call_spottedsouth96",
			"EN_call_spottedsouth97",
			"EN_call_spottedsouth98",
			"EN_call_spottedsouth99",
			"EN_call_spottedsouth100"
		};
		calloutsSW[] = {
			"EN_call_spottedsouthwest01",
			"EN_call_spottedsouthwest02",
			"EN_call_spottedsouthwest03",
			"EN_call_spottedsouthwest04",
			"EN_call_spottedsouthwest05",
			"EN_call_spottedsouthwest06",
			"EN_call_spottedsouthwest07",
			"EN_call_spottedsouthwest08",
			"EN_call_spottedsouthwest09",
			"EN_call_spottedsouthwest10",
			"EN_call_spottedsouthwest11",
			"EN_call_spottedsouthwest12",
			"EN_call_spottedsouthwest13",
			"EN_call_spottedsouthwest14",
			"EN_call_spottedsouthwest15",
			"EN_call_spottedsouthwest16",
			"EN_call_spottedsouthwest17",
			"EN_call_spottedsouthwest18",
			"EN_call_spottedsouthwest19",
			"EN_call_spottedsouthwest20",
			"EN_call_spottedsouthwest21",
			"EN_call_spottedsouthwest22",
			"EN_call_spottedsouthwest23",
			"EN_call_spottedsouthwest24",
			"EN_call_spottedsouthwest25",
			"EN_call_spottedsouthwest26",
			"EN_call_spottedsouthwest27",
			"EN_call_spottedsouthwest28",
			"EN_call_spottedsouthwest29",
			"EN_call_spottedsouthwest30",
			"EN_call_spottedsouthwest31",
			"EN_call_spottedsouthwest32",
			"EN_call_spottedsouthwest33",
			"EN_call_spottedsouthwest34",
			"EN_call_spottedsouthwest35",
			"EN_call_spottedsouthwest36",
			"EN_call_spottedsouthwest37",
			"EN_call_spottedsouthwest38",
			"EN_call_spottedsouthwest39",
			"EN_call_spottedsouthwest40",
			"EN_call_spottedsouthwest41",
			"EN_call_spottedsouthwest42",
			"EN_call_spottedsouthwest43",
			"EN_call_spottedsouthwest44",
			"EN_call_spottedsouthwest45",
			"EN_call_spottedsouthwest46",
			"EN_call_spottedsouthwest47",
			"EN_call_spottedsouthwest48",
			"EN_call_spottedsouthwest49",
			"EN_call_spottedsouthwest50",
			"EN_call_spottedsouthwest51",
			"EN_call_spottedsouthwest52",
			"EN_call_spottedsouthwest53",
			"EN_call_spottedsouthwest54",
			"EN_call_spottedsouthwest55",
			"EN_call_spottedsouthwest56",
			"EN_call_spottedsouthwest57",
			"EN_call_spottedsouthwest58",
			"EN_call_spottedsouthwest59",
			"EN_call_spottedsouthwest60",
			"EN_call_spottedsouthwest61",
			"EN_call_spottedsouthwest62",
			"EN_call_spottedsouthwest63",
			"EN_call_spottedsouthwest64",
			"EN_call_spottedsouthwest65",
			"EN_call_spottedsouthwest66",
			"EN_call_spottedsouthwest67",
			"EN_call_spottedsouthwest68",
			"EN_call_spottedsouthwest69",
			"EN_call_spottedsouthwest70",
			"EN_call_spottedsouthwest71",
			"EN_call_spottedsouthwest72",
			"EN_call_spottedsouthwest73",
			"EN_call_spottedsouthwest74",
			"EN_call_spottedsouthwest75",
			"EN_call_spottedsouthwest76",
			"EN_call_spottedsouthwest77",
			"EN_call_spottedsouthwest78",
			"EN_call_spottedsouthwest79",
			"EN_call_spottedsouthwest80",
			"EN_call_spottedsouthwest81",
			"EN_call_spottedsouthwest82",
			"EN_call_spottedsouthwest83",
			"EN_call_spottedsouthwest84",
			"EN_call_spottedsouthwest85",
			"EN_call_spottedsouthwest86",
			"EN_call_spottedsouthwest87",
			"EN_call_spottedsouthwest88",
			"EN_call_spottedsouthwest89",
			"EN_call_spottedsouthwest90",
			"EN_call_spottedsouthwest91",
			"EN_call_spottedsouthwest92",
			"EN_call_spottedsouthwest93",
			"EN_call_spottedsouthwest94",
			"EN_call_spottedsouthwest95",
			"EN_call_spottedsouthwest96",
			"EN_call_spottedsouthwest97",
			"EN_call_spottedsouthwest98",
			"EN_call_spottedsouthwest99",
			"EN_call_spottedsouthwest100"
		};
		calloutsW[] = {
			"EN_call_spottedwest01",
			"EN_call_spottedwest02",
			"EN_call_spottedwest03",
			"EN_call_spottedwest04",
			"EN_call_spottedwest05",
			"EN_call_spottedwest06",
			"EN_call_spottedwest07",
			"EN_call_spottedwest08",
			"EN_call_spottedwest09",
			"EN_call_spottedwest10",
			"EN_call_spottedwest11",
			"EN_call_spottedwest12",
			"EN_call_spottedwest13",
			"EN_call_spottedwest14",
			"EN_call_spottedwest15",
			"EN_call_spottedwest16",
			"EN_call_spottedwest17",
			"EN_call_spottedwest18",
			"EN_call_spottedwest19",
			"EN_call_spottedwest20",
			"EN_call_spottedwest21",
			"EN_call_spottedwest22",
			"EN_call_spottedwest23",
			"EN_call_spottedwest24",
			"EN_call_spottedwest25",
			"EN_call_spottedwest26",
			"EN_call_spottedwest27",
			"EN_call_spottedwest28",
			"EN_call_spottedwest29",
			"EN_call_spottedwest30",
			"EN_call_spottedwest31",
			"EN_call_spottedwest32",
			"EN_call_spottedwest33",
			"EN_call_spottedwest34",
			"EN_call_spottedwest35",
			"EN_call_spottedwest36",
			"EN_call_spottedwest37",
			"EN_call_spottedwest38",
			"EN_call_spottedwest39",
			"EN_call_spottedwest40",
			"EN_call_spottedwest41",
			"EN_call_spottedwest42",
			"EN_call_spottedwest43",
			"EN_call_spottedwest44",
			"EN_call_spottedwest45",
			"EN_call_spottedwest46",
			"EN_call_spottedwest47",
			"EN_call_spottedwest48",
			"EN_call_spottedwest49",
			"EN_call_spottedwest50",
			"EN_call_spottedwest51",
			"EN_call_spottedwest52",
			"EN_call_spottedwest53",
			"EN_call_spottedwest54",
			"EN_call_spottedwest55",
			"EN_call_spottedwest56",
			"EN_call_spottedwest57",
			"EN_call_spottedwest58",
			"EN_call_spottedwest59",
			"EN_call_spottedwest60",
			"EN_call_spottedwest61",
			"EN_call_spottedwest62",
			"EN_call_spottedwest63",
			"EN_call_spottedwest64",
			"EN_call_spottedwest65",
			"EN_call_spottedwest66",
			"EN_call_spottedwest67",
			"EN_call_spottedwest68",
			"EN_call_spottedwest69",
			"EN_call_spottedwest70",
			"EN_call_spottedwest71",
			"EN_call_spottedwest72",
			"EN_call_spottedwest73",
			"EN_call_spottedwest74",
			"EN_call_spottedwest75",
			"EN_call_spottedwest76",
			"EN_call_spottedwest77",
			"EN_call_spottedwest78",
			"EN_call_spottedwest79",
			"EN_call_spottedwest80",
			"EN_call_spottedwest81",
			"EN_call_spottedwest82",
			"EN_call_spottedwest83",
			"EN_call_spottedwest84",
			"EN_call_spottedwest85",
			"EN_call_spottedwest86",
			"EN_call_spottedwest87",
			"EN_call_spottedwest88",
			"EN_call_spottedwest89",
			"EN_call_spottedwest90",
			"EN_call_spottedwest91",
			"EN_call_spottedwest92",
			"EN_call_spottedwest93",
			"EN_call_spottedwest94",
			"EN_call_spottedwest95",
			"EN_call_spottedwest96",
			"EN_call_spottedwest97",
			"EN_call_spottedwest98",
			"EN_call_spottedwest99",
			"EN_call_spottedwest100"
		};
		calloutsNW[] = {
			"EN_call_spottednorthwest01",
			"EN_call_spottednorthwest02",
			"EN_call_spottednorthwest03",
			"EN_call_spottednorthwest04",
			"EN_call_spottednorthwest05",
			"EN_call_spottednorthwest06",
			"EN_call_spottednorthwest07",
			"EN_call_spottednorthwest08",
			"EN_call_spottednorthwest09",
			"EN_call_spottednorthwest10",
			"EN_call_spottednorthwest11",
			"EN_call_spottednorthwest12",
			"EN_call_spottednorthwest13",
			"EN_call_spottednorthwest14",
			"EN_call_spottednorthwest15",
			"EN_call_spottednorthwest16",
			"EN_call_spottednorthwest17",
			"EN_call_spottednorthwest18",
			"EN_call_spottednorthwest19",
			"EN_call_spottednorthwest20",
			"EN_call_spottednorthwest21",
			"EN_call_spottednorthwest22",
			"EN_call_spottednorthwest23",
			"EN_call_spottednorthwest24",
			"EN_call_spottednorthwest25",
			"EN_call_spottednorthwest26",
			"EN_call_spottednorthwest27",
			"EN_call_spottednorthwest28",
			"EN_call_spottednorthwest29",
			"EN_call_spottednorthwest30",
			"EN_call_spottednorthwest31",
			"EN_call_spottednorthwest32",
			"EN_call_spottednorthwest33",
			"EN_call_spottednorthwest34",
			"EN_call_spottednorthwest35",
			"EN_call_spottednorthwest36",
			"EN_call_spottednorthwest37",
			"EN_call_spottednorthwest38",
			"EN_call_spottednorthwest39",
			"EN_call_spottednorthwest40",
			"EN_call_spottednorthwest41",
			"EN_call_spottednorthwest42",
			"EN_call_spottednorthwest43",
			"EN_call_spottednorthwest44",
			"EN_call_spottednorthwest45",
			"EN_call_spottednorthwest46",
			"EN_call_spottednorthwest47",
			"EN_call_spottednorthwest48",
			"EN_call_spottednorthwest49",
			"EN_call_spottednorthwest50",
			"EN_call_spottednorthwest51",
			"EN_call_spottednorthwest52",
			"EN_call_spottednorthwest53",
			"EN_call_spottednorthwest54",
			"EN_call_spottednorthwest55",
			"EN_call_spottednorthwest56",
			"EN_call_spottednorthwest57",
			"EN_call_spottednorthwest58",
			"EN_call_spottednorthwest59",
			"EN_call_spottednorthwest60",
			"EN_call_spottednorthwest61",
			"EN_call_spottednorthwest62",
			"EN_call_spottednorthwest63",
			"EN_call_spottednorthwest64",
			"EN_call_spottednorthwest65",
			"EN_call_spottednorthwest66",
			"EN_call_spottednorthwest67",
			"EN_call_spottednorthwest68",
			"EN_call_spottednorthwest69",
			"EN_call_spottednorthwest70",
			"EN_call_spottednorthwest71",
			"EN_call_spottednorthwest72",
			"EN_call_spottednorthwest73",
			"EN_call_spottednorthwest74",
			"EN_call_spottednorthwest75",
			"EN_call_spottednorthwest76",
			"EN_call_spottednorthwest77",
			"EN_call_spottednorthwest78",
			"EN_call_spottednorthwest79",
			"EN_call_spottednorthwest80",
			"EN_call_spottednorthwest81",
			"EN_call_spottednorthwest82",
			"EN_call_spottednorthwest83",
			"EN_call_spottednorthwest84",
			"EN_call_spottednorthwest85",
			"EN_call_spottednorthwest86",
			"EN_call_spottednorthwest87",
			"EN_call_spottednorthwest88",
			"EN_call_spottednorthwest89",
			"EN_call_spottednorthwest90",
			"EN_call_spottednorthwest91",
			"EN_call_spottednorthwest92",
			"EN_call_spottednorthwest93",
			"EN_call_spottednorthwest94",
			"EN_call_spottednorthwest95",
			"EN_call_spottednorthwest96",
			"EN_call_spottednorthwest97",
			"EN_call_spottednorthwest98",
			"EN_call_spottednorthwest99",
			"EN_call_spottednorthwest100"
		};
		frag[] = {
			"EN_warning_frag01",
			"EN_warning_frag02",
			"EN_warning_frag03",
			"EN_warning_frag04",
			"EN_warning_frag05",
			"EN_warning_frag06",
			"EN_warning_frag07",
			"EN_warning_frag08",
			"EN_warning_frag09",
			"EN_warning_frag10",
			"EN_warning_frag11",
			"EN_warning_frag12",
			"EN_warning_frag13",
			"EN_warning_frag14",
			"EN_warning_frag15",
			"EN_warning_frag16",
			"EN_warning_frag17",
			"EN_warning_frag18",
			"EN_warning_frag19",
			"EN_warning_frag20",
			"EN_warning_frag21",
			"EN_warning_frag22",
			"EN_warning_frag23",
			"EN_warning_frag24",
			"EN_warning_frag25",
			"EN_warning_frag26",
			"EN_warning_frag27",
			"EN_warning_frag28",
			"EN_warning_frag29",
			"EN_warning_frag30",
			"EN_warning_frag31",
			"EN_warning_frag32",
			"EN_warning_frag33",
			"EN_warning_frag34",
			"EN_warning_frag35",
			"EN_warning_frag36",
			"EN_warning_frag37",
			"EN_warning_frag38",
			"EN_warning_frag39",
			"EN_warning_frag40",
			"EN_warning_frag41",
			"EN_warning_frag42",
			"EN_warning_frag43",
			"EN_warning_frag44",
			"EN_warning_frag45",
			"EN_warning_frag46",
			"EN_warning_frag47",
			"EN_warning_frag48",
			"EN_warning_frag49",
			"EN_warning_frag50",
			"EN_warning_frag51",
			"EN_warning_frag52",
			"EN_warning_frag53",
			"EN_warning_frag54",
			"EN_warning_frag55",
			"EN_warning_frag56",
			"EN_warning_frag57",
			"EN_warning_frag58",
			"EN_warning_frag59",
			"EN_warning_frag60",
			"EN_warning_frag61",
			"EN_warning_frag62",
			"EN_warning_frag63",
			"EN_warning_frag64",
			"EN_warning_frag65",
			"EN_warning_frag66",
			"EN_warning_frag67",
			"EN_warning_frag68",
			"EN_warning_frag69",
			"EN_warning_frag70",
			"EN_warning_frag71",
			"EN_warning_frag72",
			"EN_warning_frag73",
			"EN_warning_frag74",
			"EN_warning_frag75",
			"EN_warning_frag76",
			"EN_warning_frag77",
			"EN_warning_frag78",
			"EN_warning_frag79",
			"EN_warning_frag80",
			"EN_warning_frag81",
			"EN_warning_frag82",
			"EN_warning_frag83",
			"EN_warning_frag84",
			"EN_warning_frag85",
			"EN_warning_frag86",
			"EN_warning_frag87",
			"EN_warning_frag88",
			"EN_warning_frag89",
			"EN_warning_frag90",
			"EN_warning_frag91",
			"EN_warning_frag92",
			"EN_warning_frag93",
			"EN_warning_frag94",
			"EN_warning_frag95",
			"EN_warning_frag96",
			"EN_warning_frag97",
			"EN_warning_frag98",
			"EN_warning_frag99",
			"EN_warning_frag100"
		};
		smoke[] = {
			"EN_warning_smoke01",
			"EN_warning_smoke02",
			"EN_warning_smoke03",
			"EN_warning_smoke04",
			"EN_warning_smoke05",
			"EN_warning_smoke06",
			"EN_warning_smoke07",
			"EN_warning_smoke08",
			"EN_warning_smoke09",
			"EN_warning_smoke10",
			"EN_warning_smoke11",
			"EN_warning_smoke12",
			"EN_warning_smoke13",
			"EN_warning_smoke14",
			"EN_warning_smoke15",
			"EN_warning_smoke16",
			"EN_warning_smoke17",
			"EN_warning_smoke18",
			"EN_warning_smoke19",
			"EN_warning_smoke20",
			"EN_warning_smoke21",
			"EN_warning_smoke22",
			"EN_warning_smoke23",
			"EN_warning_smoke24",
			"EN_warning_smoke25",
			"EN_warning_smoke26",
			"EN_warning_smoke27",
			"EN_warning_smoke28",
			"EN_warning_smoke29",
			"EN_warning_smoke30",
			"EN_warning_smoke31",
			"EN_warning_smoke32",
			"EN_warning_smoke33",
			"EN_warning_smoke34",
			"EN_warning_smoke35",
			"EN_warning_smoke36",
			"EN_warning_smoke37",
			"EN_warning_smoke38",
			"EN_warning_smoke39",
			"EN_warning_smoke40",
			"EN_warning_smoke41",
			"EN_warning_smoke42",
			"EN_warning_smoke43",
			"EN_warning_smoke44",
			"EN_warning_smoke45",
			"EN_warning_smoke46",
			"EN_warning_smoke47",
			"EN_warning_smoke48",
			"EN_warning_smoke49",
			"EN_warning_smoke50",
			"EN_warning_smoke51",
			"EN_warning_smoke52",
			"EN_warning_smoke53",
			"EN_warning_smoke54",
			"EN_warning_smoke55",
			"EN_warning_smoke56",
			"EN_warning_smoke57",
			"EN_warning_smoke58",
			"EN_warning_smoke59",
			"EN_warning_smoke60",
			"EN_warning_smoke61",
			"EN_warning_smoke62",
			"EN_warning_smoke63",
			"EN_warning_smoke64",
			"EN_warning_smoke65",
			"EN_warning_smoke66",
			"EN_warning_smoke67",
			"EN_warning_smoke68",
			"EN_warning_smoke69",
			"EN_warning_smoke70",
			"EN_warning_smoke71",
			"EN_warning_smoke72",
			"EN_warning_smoke73",
			"EN_warning_smoke74",
			"EN_warning_smoke75",
			"EN_warning_smoke76",
			"EN_warning_smoke77",
			"EN_warning_smoke78",
			"EN_warning_smoke79",
			"EN_warning_smoke80",
			"EN_warning_smoke81",
			"EN_warning_smoke82",
			"EN_warning_smoke83",
			"EN_warning_smoke84",
			"EN_warning_smoke85",
			"EN_warning_smoke86",
			"EN_warning_smoke87",
			"EN_warning_smoke88",
			"EN_warning_smoke89",
			"EN_warning_smoke90",
			"EN_warning_smoke91",
			"EN_warning_smoke92",
			"EN_warning_smoke93",
			"EN_warning_smoke94",
			"EN_warning_smoke95",
			"EN_warning_smoke96",
			"EN_warning_smoke97",
			"EN_warning_smoke98",
			"EN_warning_smoke99",
			"EN_warning_smoke100"
		};
		flash[] = {
			"EN_warning_frag01",
			"EN_warning_frag02",
			"EN_warning_frag03",
			"EN_warning_frag04",
			"EN_warning_frag05",
			"EN_warning_frag06",
			"EN_warning_frag07",
			"EN_warning_frag08",
			"EN_warning_frag09",
			"EN_warning_frag10",
			"EN_warning_frag11",
			"EN_warning_frag12",
			"EN_warning_frag13",
			"EN_warning_frag14",
			"EN_warning_frag15",
			"EN_warning_frag16",
			"EN_warning_frag17",
			"EN_warning_frag18",
			"EN_warning_frag19",
			"EN_warning_frag20",
			"EN_warning_frag21",
			"EN_warning_frag22",
			"EN_warning_frag23",
			"EN_warning_frag24",
			"EN_warning_frag25",
			"EN_warning_frag26",
			"EN_warning_frag27",
			"EN_warning_frag28",
			"EN_warning_frag29",
			"EN_warning_frag30",
			"EN_warning_frag31",
			"EN_warning_frag32",
			"EN_warning_frag33",
			"EN_warning_frag34",
			"EN_warning_frag35",
			"EN_warning_frag36",
			"EN_warning_frag37",
			"EN_warning_frag38",
			"EN_warning_frag39",
			"EN_warning_frag40",
			"EN_warning_frag41",
			"EN_warning_frag42",
			"EN_warning_frag43",
			"EN_warning_frag44",
			"EN_warning_frag45",
			"EN_warning_frag46",
			"EN_warning_frag47",
			"EN_warning_frag48",
			"EN_warning_frag49",
			"EN_warning_frag50",
			"EN_warning_frag51",
			"EN_warning_frag52",
			"EN_warning_frag53",
			"EN_warning_frag54",
			"EN_warning_frag55",
			"EN_warning_frag56",
			"EN_warning_frag57",
			"EN_warning_frag58",
			"EN_warning_frag59",
			"EN_warning_frag60",
			"EN_warning_frag61",
			"EN_warning_frag62",
			"EN_warning_frag63",
			"EN_warning_frag64",
			"EN_warning_frag65",
			"EN_warning_frag66",
			"EN_warning_frag67",
			"EN_warning_frag68",
			"EN_warning_frag69",
			"EN_warning_frag70",
			"EN_warning_frag71",
			"EN_warning_frag72",
			"EN_warning_frag73",
			"EN_warning_frag74",
			"EN_warning_frag75",
			"EN_warning_frag76",
			"EN_warning_frag77",
			"EN_warning_frag78",
			"EN_warning_frag79",
			"EN_warning_frag80",
			"EN_warning_frag81",
			"EN_warning_frag82",
			"EN_warning_frag83",
			"EN_warning_frag84",
			"EN_warning_frag85",
			"EN_warning_frag86",
			"EN_warning_frag87",
			"EN_warning_frag88",
			"EN_warning_frag89",
			"EN_warning_frag90",
			"EN_warning_frag91",
			"EN_warning_frag92",
			"EN_warning_frag93",
			"EN_warning_frag94",
			"EN_warning_frag95",
			"EN_warning_frag96",
			"EN_warning_frag97",
			"EN_warning_frag98",
			"EN_warning_frag99",
			"EN_warning_frag100"
		};
		incendiary[] = {
			"EN_warning_frag01",
			"EN_warning_frag02",
			"EN_warning_frag03",
			"EN_warning_frag04",
			"EN_warning_frag05",
			"EN_warning_frag06",
			"EN_warning_frag07",
			"EN_warning_frag08",
			"EN_warning_frag09",
			"EN_warning_frag10",
			"EN_warning_frag11",
			"EN_warning_frag12",
			"EN_warning_frag13",
			"EN_warning_frag14",
			"EN_warning_frag15",
			"EN_warning_frag16",
			"EN_warning_frag17",
			"EN_warning_frag18",
			"EN_warning_frag19",
			"EN_warning_frag20",
			"EN_warning_frag21",
			"EN_warning_frag22",
			"EN_warning_frag23",
			"EN_warning_frag24",
			"EN_warning_frag25",
			"EN_warning_frag26",
			"EN_warning_frag27",
			"EN_warning_frag28",
			"EN_warning_frag29",
			"EN_warning_frag30",
			"EN_warning_frag31",
			"EN_warning_frag32",
			"EN_warning_frag33",
			"EN_warning_frag34",
			"EN_warning_frag35",
			"EN_warning_frag36",
			"EN_warning_frag37",
			"EN_warning_frag38",
			"EN_warning_frag39",
			"EN_warning_frag40",
			"EN_warning_frag41",
			"EN_warning_frag42",
			"EN_warning_frag43",
			"EN_warning_frag44",
			"EN_warning_frag45",
			"EN_warning_frag46",
			"EN_warning_frag47",
			"EN_warning_frag48",
			"EN_warning_frag49",
			"EN_warning_frag50",
			"EN_warning_frag51",
			"EN_warning_frag52",
			"EN_warning_frag53",
			"EN_warning_frag54",
			"EN_warning_frag55",
			"EN_warning_frag56",
			"EN_warning_frag57",
			"EN_warning_frag58",
			"EN_warning_frag59",
			"EN_warning_frag60",
			"EN_warning_frag61",
			"EN_warning_frag62",
			"EN_warning_frag63",
			"EN_warning_frag64",
			"EN_warning_frag65",
			"EN_warning_frag66",
			"EN_warning_frag67",
			"EN_warning_frag68",
			"EN_warning_frag69",
			"EN_warning_frag70",
			"EN_warning_frag71",
			"EN_warning_frag72",
			"EN_warning_frag73",
			"EN_warning_frag74",
			"EN_warning_frag75",
			"EN_warning_frag76",
			"EN_warning_frag77",
			"EN_warning_frag78",
			"EN_warning_frag79",
			"EN_warning_frag80",
			"EN_warning_frag81",
			"EN_warning_frag82",
			"EN_warning_frag83",
			"EN_warning_frag84",
			"EN_warning_frag85",
			"EN_warning_frag86",
			"EN_warning_frag87",
			"EN_warning_frag88",
			"EN_warning_frag89",
			"EN_warning_frag90",
			"EN_warning_frag91",
			"EN_warning_frag92",
			"EN_warning_frag93",
			"EN_warning_frag94",
			"EN_warning_frag95",
			"EN_warning_frag96",
			"EN_warning_frag97",
			"EN_warning_frag98",
			"EN_warning_frag99",
			"EN_warning_frag100"
		};
		explosive[] = {
			"EN_warning_spottedexplosive01",
			"EN_warning_spottedexplosive02",
			"EN_warning_spottedexplosive03",
			"EN_warning_spottedexplosive04",
			"EN_warning_spottedexplosive05",
			"EN_warning_spottedexplosive06",
			"EN_warning_spottedexplosive07",
			"EN_warning_spottedexplosive08",
			"EN_warning_spottedexplosive09",
			"EN_warning_spottedexplosive10",
			"EN_warning_spottedexplosive11",
			"EN_warning_spottedexplosive12",
			"EN_warning_spottedexplosive13",
			"EN_warning_spottedexplosive14",
			"EN_warning_spottedexplosive15",
			"EN_warning_spottedexplosive16",
			"EN_warning_spottedexplosive17",
			"EN_warning_spottedexplosive18",
			"EN_warning_spottedexplosive19",
			"EN_warning_spottedexplosive20",
			"EN_warning_spottedexplosive21",
			"EN_warning_spottedexplosive22",
			"EN_warning_spottedexplosive23",
			"EN_warning_spottedexplosive24",
			"EN_warning_spottedexplosive25",
			"EN_warning_spottedexplosive26",
			"EN_warning_spottedexplosive27",
			"EN_warning_spottedexplosive28",
			"EN_warning_spottedexplosive29",
			"EN_warning_spottedexplosive30",
			"EN_warning_spottedexplosive31",
			"EN_warning_spottedexplosive32",
			"EN_warning_spottedexplosive33",
			"EN_warning_spottedexplosive34",
			"EN_warning_spottedexplosive35",
			"EN_warning_spottedexplosive36",
			"EN_warning_spottedexplosive37",
			"EN_warning_spottedexplosive38",
			"EN_warning_spottedexplosive39",
			"EN_warning_spottedexplosive40",
			"EN_warning_spottedexplosive41",
			"EN_warning_spottedexplosive42",
			"EN_warning_spottedexplosive43",
			"EN_warning_spottedexplosive44",
			"EN_warning_spottedexplosive45",
			"EN_warning_spottedexplosive46",
			"EN_warning_spottedexplosive47",
			"EN_warning_spottedexplosive48",
			"EN_warning_spottedexplosive49",
			"EN_warning_spottedexplosive50",
			"EN_warning_spottedexplosive51",
			"EN_warning_spottedexplosive52",
			"EN_warning_spottedexplosive53",
			"EN_warning_spottedexplosive54",
			"EN_warning_spottedexplosive55",
			"EN_warning_spottedexplosive56",
			"EN_warning_spottedexplosive57",
			"EN_warning_spottedexplosive58",
			"EN_warning_spottedexplosive59",
			"EN_warning_spottedexplosive60",
			"EN_warning_spottedexplosive61",
			"EN_warning_spottedexplosive62",
			"EN_warning_spottedexplosive63",
			"EN_warning_spottedexplosive64",
			"EN_warning_spottedexplosive65",
			"EN_warning_spottedexplosive66",
			"EN_warning_spottedexplosive67",
			"EN_warning_spottedexplosive68",
			"EN_warning_spottedexplosive69",
			"EN_warning_spottedexplosive70",
			"EN_warning_spottedexplosive71",
			"EN_warning_spottedexplosive72",
			"EN_warning_spottedexplosive73",
			"EN_warning_spottedexplosive74",
			"EN_warning_spottedexplosive75",
			"EN_warning_spottedexplosive76",
			"EN_warning_spottedexplosive77",
			"EN_warning_spottedexplosive78",
			"EN_warning_spottedexplosive79",
			"EN_warning_spottedexplosive80",
			"EN_warning_spottedexplosive81",
			"EN_warning_spottedexplosive82",
			"EN_warning_spottedexplosive83",
			"EN_warning_spottedexplosive84",
			"EN_warning_spottedexplosive85",
			"EN_warning_spottedexplosive86",
			"EN_warning_spottedexplosive87",
			"EN_warning_spottedexplosive88",
			"EN_warning_spottedexplosive89",
			"EN_warning_spottedexplosive90",
			"EN_warning_spottedexplosive91",
			"EN_warning_spottedexplosive92",
			"EN_warning_spottedexplosive93",
			"EN_warning_spottedexplosive94",
			"EN_warning_spottedexplosive95",
			"EN_warning_spottedexplosive96",
			"EN_warning_spottedexplosive97",
			"EN_warning_spottedexplosive98",
			"EN_warning_spottedexplosive99",
			"EN_warning_spottedexplosive100"
		};
		spotNade[] = {
			"EN_warning_spottednade01",
			"EN_warning_spottednade02",
			"EN_warning_spottednade03",
			"EN_warning_spottednade04",
			"EN_warning_spottednade05",
			"EN_warning_spottednade06",
			"EN_warning_spottednade07",
			"EN_warning_spottednade08",
			"EN_warning_spottednade09",
			"EN_warning_spottednade10",
			"EN_warning_spottednade11",
			"EN_warning_spottednade12",
			"EN_warning_spottednade13",
			"EN_warning_spottednade14",
			"EN_warning_spottednade15",
			"EN_warning_spottednade16",
			"EN_warning_spottednade17",
			"EN_warning_spottednade18",
			"EN_warning_spottednade19",
			"EN_warning_spottednade20",
			"EN_warning_spottednade21",
			"EN_warning_spottednade22",
			"EN_warning_spottednade23",
			"EN_warning_spottednade24",
			"EN_warning_spottednade25",
			"EN_warning_spottednade26",
			"EN_warning_spottednade27",
			"EN_warning_spottednade28",
			"EN_warning_spottednade29",
			"EN_warning_spottednade30",
			"EN_warning_spottednade31",
			"EN_warning_spottednade32",
			"EN_warning_spottednade33",
			"EN_warning_spottednade34",
			"EN_warning_spottednade35",
			"EN_warning_spottednade36",
			"EN_warning_spottednade37",
			"EN_warning_spottednade38",
			"EN_warning_spottednade39",
			"EN_warning_spottednade40",
			"EN_warning_spottednade41",
			"EN_warning_spottednade42",
			"EN_warning_spottednade43",
			"EN_warning_spottednade44",
			"EN_warning_spottednade45",
			"EN_warning_spottednade46",
			"EN_warning_spottednade47",
			"EN_warning_spottednade48",
			"EN_warning_spottednade49",
			"EN_warning_spottednade50",
			"EN_warning_spottednade51",
			"EN_warning_spottednade52",
			"EN_warning_spottednade53",
			"EN_warning_spottednade54",
			"EN_warning_spottednade55",
			"EN_warning_spottednade56",
			"EN_warning_spottednade57",
			"EN_warning_spottednade58",
			"EN_warning_spottednade59",
			"EN_warning_spottednade60",
			"EN_warning_spottednade61",
			"EN_warning_spottednade62",
			"EN_warning_spottednade63",
			"EN_warning_spottednade64",
			"EN_warning_spottednade65",
			"EN_warning_spottednade66",
			"EN_warning_spottednade67",
			"EN_warning_spottednade68",
			"EN_warning_spottednade69",
			"EN_warning_spottednade70",
			"EN_warning_spottednade71",
			"EN_warning_spottednade72",
			"EN_warning_spottednade73",
			"EN_warning_spottednade74",
			"EN_warning_spottednade75",
			"EN_warning_spottednade76",
			"EN_warning_spottednade77",
			"EN_warning_spottednade78",
			"EN_warning_spottednade79",
			"EN_warning_spottednade80",
			"EN_warning_spottednade81",
			"EN_warning_spottednade82",
			"EN_warning_spottednade83",
			"EN_warning_spottednade84",
			"EN_warning_spottednade85",
			"EN_warning_spottednade86",
			"EN_warning_spottednade87",
			"EN_warning_spottednade88",
			"EN_warning_spottednade89",
			"EN_warning_spottednade90",
			"EN_warning_spottednade91",
			"EN_warning_spottednade92",
			"EN_warning_spottednade93",
			"EN_warning_spottednade94",
			"EN_warning_spottednade95",
			"EN_warning_spottednade96",
			"EN_warning_spottednade97",
			"EN_warning_spottednade98",
			"EN_warning_spottednade99",
			"EN_warning_spottednade100"
		};
		friendlyFire[] = {
			"EN_hit_friendlyfire01",
			"EN_hit_friendlyfire02",
			"EN_hit_friendlyfire03",
			"EN_hit_friendlyfire04",
			"EN_hit_friendlyfire05",
			"EN_hit_friendlyfire06",
			"EN_hit_friendlyfire07",
			"EN_hit_friendlyfire08",
			"EN_hit_friendlyfire09",
			"EN_hit_friendlyfire10",
			"EN_hit_friendlyfire11",
			"EN_hit_friendlyfire12",
			"EN_hit_friendlyfire13",
			"EN_hit_friendlyfire14",
			"EN_hit_friendlyfire15",
			"EN_hit_friendlyfire16",
			"EN_hit_friendlyfire17",
			"EN_hit_friendlyfire18",
			"EN_hit_friendlyfire19",
			"EN_hit_friendlyfire20",
			"EN_hit_friendlyfire21",
			"EN_hit_friendlyfire22",
			"EN_hit_friendlyfire23",
			"EN_hit_friendlyfire24",
			"EN_hit_friendlyfire25",
			"EN_hit_friendlyfire26",
			"EN_hit_friendlyfire27",
			"EN_hit_friendlyfire28",
			"EN_hit_friendlyfire29",
			"EN_hit_friendlyfire30",
			"EN_hit_friendlyfire31",
			"EN_hit_friendlyfire32",
			"EN_hit_friendlyfire33",
			"EN_hit_friendlyfire34",
			"EN_hit_friendlyfire35",
			"EN_hit_friendlyfire36",
			"EN_hit_friendlyfire37",
			"EN_hit_friendlyfire38",
			"EN_hit_friendlyfire39",
			"EN_hit_friendlyfire40",
			"EN_hit_friendlyfire41",
			"EN_hit_friendlyfire42",
			"EN_hit_friendlyfire43",
			"EN_hit_friendlyfire44",
			"EN_hit_friendlyfire45",
			"EN_hit_friendlyfire46",
			"EN_hit_friendlyfire47",
			"EN_hit_friendlyfire48",
			"EN_hit_friendlyfire49",
			"EN_hit_friendlyfire50",
			"EN_hit_friendlyfire51",
			"EN_hit_friendlyfire52",
			"EN_hit_friendlyfire53",
			"EN_hit_friendlyfire54",
			"EN_hit_friendlyfire55",
			"EN_hit_friendlyfire56",
			"EN_hit_friendlyfire57",
			"EN_hit_friendlyfire58",
			"EN_hit_friendlyfire59",
			"EN_hit_friendlyfire60",
			"EN_hit_friendlyfire61",
			"EN_hit_friendlyfire62",
			"EN_hit_friendlyfire63",
			"EN_hit_friendlyfire64",
			"EN_hit_friendlyfire65",
			"EN_hit_friendlyfire66",
			"EN_hit_friendlyfire67",
			"EN_hit_friendlyfire68",
			"EN_hit_friendlyfire69",
			"EN_hit_friendlyfire70",
			"EN_hit_friendlyfire71",
			"EN_hit_friendlyfire72",
			"EN_hit_friendlyfire73",
			"EN_hit_friendlyfire74",
			"EN_hit_friendlyfire75",
			"EN_hit_friendlyfire76",
			"EN_hit_friendlyfire77",
			"EN_hit_friendlyfire78",
			"EN_hit_friendlyfire79",
			"EN_hit_friendlyfire80",
			"EN_hit_friendlyfire81",
			"EN_hit_friendlyfire82",
			"EN_hit_friendlyfire83",
			"EN_hit_friendlyfire84",
			"EN_hit_friendlyfire85",
			"EN_hit_friendlyfire86",
			"EN_hit_friendlyfire87",
			"EN_hit_friendlyfire88",
			"EN_hit_friendlyfire89",
			"EN_hit_friendlyfire90",
			"EN_hit_friendlyfire91",
			"EN_hit_friendlyfire92",
			"EN_hit_friendlyfire93",
			"EN_hit_friendlyfire94",
			"EN_hit_friendlyfire95",
			"EN_hit_friendlyfire96",
			"EN_hit_friendlyfire97",
			"EN_hit_friendlyfire98",
			"EN_hit_friendlyfire99",
			"EN_hit_friendlyfire100"
		};
		wounded[] = {
			"EN_hit_wounded01",
			"EN_hit_wounded02",
			"EN_hit_wounded03",
			"EN_hit_wounded04",
			"EN_hit_wounded05",
			"EN_hit_wounded06",
			"EN_hit_wounded07",
			"EN_hit_wounded08",
			"EN_hit_wounded09",
			"EN_hit_wounded10",
			"EN_hit_wounded11",
			"EN_hit_wounded12",
			"EN_hit_wounded13",
			"EN_hit_wounded14",
			"EN_hit_wounded15",
			"EN_hit_wounded16",
			"EN_hit_wounded17",
			"EN_hit_wounded18",
			"EN_hit_wounded19",
			"EN_hit_wounded20",
			"EN_hit_wounded21",
			"EN_hit_wounded22",
			"EN_hit_wounded23",
			"EN_hit_wounded24",
			"EN_hit_wounded25",
			"EN_hit_wounded26",
			"EN_hit_wounded27",
			"EN_hit_wounded28",
			"EN_hit_wounded29",
			"EN_hit_wounded30",
			"EN_hit_wounded31",
			"EN_hit_wounded32",
			"EN_hit_wounded33",
			"EN_hit_wounded34",
			"EN_hit_wounded35",
			"EN_hit_wounded36",
			"EN_hit_wounded37",
			"EN_hit_wounded38",
			"EN_hit_wounded39",
			"EN_hit_wounded40",
			"EN_hit_wounded41",
			"EN_hit_wounded42",
			"EN_hit_wounded43",
			"EN_hit_wounded44",
			"EN_hit_wounded45",
			"EN_hit_wounded46",
			"EN_hit_wounded47",
			"EN_hit_wounded48",
			"EN_hit_wounded49",
			"EN_hit_wounded50",
			"EN_hit_wounded51",
			"EN_hit_wounded52",
			"EN_hit_wounded53",
			"EN_hit_wounded54",
			"EN_hit_wounded55",
			"EN_hit_wounded56",
			"EN_hit_wounded57",
			"EN_hit_wounded58",
			"EN_hit_wounded59",
			"EN_hit_wounded60",
			"EN_hit_wounded61",
			"EN_hit_wounded62",
			"EN_hit_wounded63",
			"EN_hit_wounded64",
			"EN_hit_wounded65",
			"EN_hit_wounded66",
			"EN_hit_wounded67",
			"EN_hit_wounded68",
			"EN_hit_wounded69",
			"EN_hit_wounded70",
			"EN_hit_wounded71",
			"EN_hit_wounded72",
			"EN_hit_wounded73",
			"EN_hit_wounded74",
			"EN_hit_wounded75",
			"EN_hit_wounded76",
			"EN_hit_wounded77",
			"EN_hit_wounded78",
			"EN_hit_wounded79",
			"EN_hit_wounded80",
			"EN_hit_wounded81",
			"EN_hit_wounded82",
			"EN_hit_wounded83",
			"EN_hit_wounded84",
			"EN_hit_wounded85",
			"EN_hit_wounded86",
			"EN_hit_wounded87",
			"EN_hit_wounded88",
			"EN_hit_wounded89",
			"EN_hit_wounded90",
			"EN_hit_wounded91",
			"EN_hit_wounded92",
			"EN_hit_wounded93",
			"EN_hit_wounded94",
			"EN_hit_wounded95",
			"EN_hit_wounded96",
			"EN_hit_wounded97",
			"EN_hit_wounded98",
			"EN_hit_wounded99",
			"EN_hit_wounded100"
		};
		allyDown[] = {
			"EN_hit_allydown01",
			"EN_hit_allydown02",
			"EN_hit_allydown03",
			"EN_hit_allydown04",
			"EN_hit_allydown05",
			"EN_hit_allydown06",
			"EN_hit_allydown07",
			"EN_hit_allydown08",
			"EN_hit_allydown09",
			"EN_hit_allydown10",
			"EN_hit_allydown11",
			"EN_hit_allydown12",
			"EN_hit_allydown13",
			"EN_hit_allydown14",
			"EN_hit_allydown15",
			"EN_hit_allydown16",
			"EN_hit_allydown17",
			"EN_hit_allydown18",
			"EN_hit_allydown19",
			"EN_hit_allydown20",
			"EN_hit_allydown21",
			"EN_hit_allydown22",
			"EN_hit_allydown23",
			"EN_hit_allydown24",
			"EN_hit_allydown25",
			"EN_hit_allydown26",
			"EN_hit_allydown27",
			"EN_hit_allydown28",
			"EN_hit_allydown29",
			"EN_hit_allydown30",
			"EN_hit_allydown31",
			"EN_hit_allydown32",
			"EN_hit_allydown33",
			"EN_hit_allydown34",
			"EN_hit_allydown35",
			"EN_hit_allydown36",
			"EN_hit_allydown37",
			"EN_hit_allydown38",
			"EN_hit_allydown39",
			"EN_hit_allydown40",
			"EN_hit_allydown41",
			"EN_hit_allydown42",
			"EN_hit_allydown43",
			"EN_hit_allydown44",
			"EN_hit_allydown45",
			"EN_hit_allydown46",
			"EN_hit_allydown47",
			"EN_hit_allydown48",
			"EN_hit_allydown49",
			"EN_hit_allydown50",
			"EN_hit_allydown51",
			"EN_hit_allydown52",
			"EN_hit_allydown53",
			"EN_hit_allydown54",
			"EN_hit_allydown55",
			"EN_hit_allydown56",
			"EN_hit_allydown57",
			"EN_hit_allydown58",
			"EN_hit_allydown59",
			"EN_hit_allydown60",
			"EN_hit_allydown61",
			"EN_hit_allydown62",
			"EN_hit_allydown63",
			"EN_hit_allydown64",
			"EN_hit_allydown65",
			"EN_hit_allydown66",
			"EN_hit_allydown67",
			"EN_hit_allydown68",
			"EN_hit_allydown69",
			"EN_hit_allydown70",
			"EN_hit_allydown71",
			"EN_hit_allydown72",
			"EN_hit_allydown73",
			"EN_hit_allydown74",
			"EN_hit_allydown75",
			"EN_hit_allydown76",
			"EN_hit_allydown77",
			"EN_hit_allydown78",
			"EN_hit_allydown79",
			"EN_hit_allydown80",
			"EN_hit_allydown81",
			"EN_hit_allydown82",
			"EN_hit_allydown83",
			"EN_hit_allydown84",
			"EN_hit_allydown85",
			"EN_hit_allydown86",
			"EN_hit_allydown87",
			"EN_hit_allydown88",
			"EN_hit_allydown89",
			"EN_hit_allydown90",
			"EN_hit_allydown91",
			"EN_hit_allydown92",
			"EN_hit_allydown93",
			"EN_hit_allydown94",
			"EN_hit_allydown95",
			"EN_hit_allydown96",
			"EN_hit_allydown97",
			"EN_hit_allydown98",
			"EN_hit_allydown99",
			"EN_hit_allydown100",
			"EN_killed_allydown01",
			"EN_killed_allydown02",
			"EN_killed_allydown03",
			"EN_killed_allydown04",
			"EN_killed_allydown05",
			"EN_killed_allydown06",
			"EN_killed_allydown07",
			"EN_killed_allydown08",
			"EN_killed_allydown09",
			"EN_killed_allydown10",
			"EN_killed_allydown11",
			"EN_killed_allydown12",
			"EN_killed_allydown13",
			"EN_killed_allydown14",
			"EN_killed_allydown15",
			"EN_killed_allydown16",
			"EN_killed_allydown17",
			"EN_killed_allydown18",
			"EN_killed_allydown19",
			"EN_killed_allydown20",
			"EN_killed_allydown21",
			"EN_killed_allydown22",
			"EN_killed_allydown23",
			"EN_killed_allydown24",
			"EN_killed_allydown25",
			"EN_killed_allydown26",
			"EN_killed_allydown27",
			"EN_killed_allydown28",
			"EN_killed_allydown29",
			"EN_killed_allydown30",
			"EN_killed_allydown31",
			"EN_killed_allydown32",
			"EN_killed_allydown33",
			"EN_killed_allydown34",
			"EN_killed_allydown35"
		};
		targDownHi[] = {
			"EN_call_targdown01",
			"EN_call_targdown02",
			"EN_call_targdown03",
			"EN_call_targdown04",
			"EN_call_targdown05",
			"EN_call_targdown06",
			"EN_call_targdown07",
			"EN_call_targdown08",
			"EN_call_targdown09",
			"EN_call_targdown10",
			"EN_call_targdown11",
			"EN_call_targdown12",
			"EN_call_targdown13",
			"EN_call_targdown14",
			"EN_call_targdown15",
			"EN_call_targdown16",
			"EN_call_targdown17",
			"EN_call_targdown18",
			"EN_call_targdown19",
			"EN_call_targdown20",
			"EN_call_targdown21",
			"EN_call_targdown22",
			"EN_call_targdown23",
			"EN_call_targdown24",
			"EN_call_targdown25",
			"EN_call_targdown26",
			"EN_call_targdown27",
			"EN_call_targdown28",
			"EN_call_targdown29",
			"EN_call_targdown30",
			"EN_call_targdown31",
			"EN_call_targdown32",
			"EN_call_targdown33",
			"EN_call_targdown34",
			"EN_call_targdown35",
			"EN_call_targdown36",
			"EN_call_targdown37",
			"EN_call_targdown38",
			"EN_call_targdown39",
			"EN_call_targdown40",
			"EN_call_targdown41",
			"EN_call_targdown42",
			"EN_call_targdown43",
			"EN_call_targdown44",
			"EN_call_targdown45",
			"EN_call_targdown46",
			"EN_call_targdown47",
			"EN_call_targdown48",
			"EN_call_targdown49",
			"EN_call_targdown50",
			"EN_call_targdown51",
			"EN_call_targdown52",
			"EN_call_targdown53",
			"EN_call_targdown54",
			"EN_call_targdown55",
			"EN_call_targdown56",
			"EN_call_targdown57",
			"EN_call_targdown58",
			"EN_call_targdown59",
			"EN_call_targdown60",
			"EN_call_targdown61",
			"EN_call_targdown62",
			"EN_call_targdown63",
			"EN_call_targdown64",
			"EN_call_targdown65",
			"EN_call_targdown66",
			"EN_call_targdown67",
			"EN_call_targdown68",
			"EN_call_targdown69",
			"EN_call_targdown70",
			"EN_call_targdown71",
			"EN_call_targdown72",
			"EN_call_targdown73",
			"EN_call_targdown74",
			"EN_call_targdown75",
			"EN_call_targdown76",
			"EN_call_targdown77",
			"EN_call_targdown78",
			"EN_call_targdown79",
			"EN_call_targdown80",
			"EN_call_targdown81",
			"EN_call_targdown82",
			"EN_call_targdown83",
			"EN_call_targdown84",
			"EN_call_targdown85",
			"EN_call_targdown86",
			"EN_call_targdown87",
			"EN_call_targdown88",
			"EN_call_targdown89",
			"EN_call_targdown90",
			"EN_call_targdown91",
			"EN_call_targdown92",
			"EN_call_targdown93",
			"EN_call_targdown94",
			"EN_call_targdown95",
			"EN_call_targdown96",
			"EN_call_targdown97",
			"EN_call_targdown98",
			"EN_call_targdown99",
			"EN_call_targdown100"
		};
		targDownLo[] = {
			"EN_call_targdown01",
			"EN_call_targdown02",
			"EN_call_targdown03",
			"EN_call_targdown04",
			"EN_call_targdown05",
			"EN_call_targdown06",
			"EN_call_targdown07",
			"EN_call_targdown08",
			"EN_call_targdown09",
			"EN_call_targdown10",
			"EN_call_targdown11",
			"EN_call_targdown12",
			"EN_call_targdown13",
			"EN_call_targdown14",
			"EN_call_targdown15",
			"EN_call_targdown16",
			"EN_call_targdown17",
			"EN_call_targdown18",
			"EN_call_targdown19",
			"EN_call_targdown20",
			"EN_call_targdown21",
			"EN_call_targdown22",
			"EN_call_targdown23",
			"EN_call_targdown24",
			"EN_call_targdown25",
			"EN_call_targdown26",
			"EN_call_targdown27",
			"EN_call_targdown28",
			"EN_call_targdown29",
			"EN_call_targdown30",
			"EN_call_targdown31",
			"EN_call_targdown32",
			"EN_call_targdown33",
			"EN_call_targdown34",
			"EN_call_targdown35",
			"EN_call_targdown36",
			"EN_call_targdown37",
			"EN_call_targdown38",
			"EN_call_targdown39",
			"EN_call_targdown40",
			"EN_call_targdown41",
			"EN_call_targdown42",
			"EN_call_targdown43",
			"EN_call_targdown44",
			"EN_call_targdown45",
			"EN_call_targdown46",
			"EN_call_targdown47",
			"EN_call_targdown48",
			"EN_call_targdown49",
			"EN_call_targdown50",
			"EN_call_targdown51",
			"EN_call_targdown52",
			"EN_call_targdown53",
			"EN_call_targdown54",
			"EN_call_targdown55",
			"EN_call_targdown56",
			"EN_call_targdown57",
			"EN_call_targdown58",
			"EN_call_targdown59",
			"EN_call_targdown60",
			"EN_call_targdown61",
			"EN_call_targdown62",
			"EN_call_targdown63",
			"EN_call_targdown64",
			"EN_call_targdown65",
			"EN_call_targdown66",
			"EN_call_targdown67",
			"EN_call_targdown68",
			"EN_call_targdown69",
			"EN_call_targdown70",
			"EN_call_targdown71",
			"EN_call_targdown72",
			"EN_call_targdown73",
			"EN_call_targdown74",
			"EN_call_targdown75",
			"EN_call_targdown76",
			"EN_call_targdown77",
			"EN_call_targdown78",
			"EN_call_targdown79",
			"EN_call_targdown80",
			"EN_call_targdown81",
			"EN_call_targdown82",
			"EN_call_targdown83",
			"EN_call_targdown84",
			"EN_call_targdown85",
			"EN_call_targdown86",
			"EN_call_targdown87",
			"EN_call_targdown88",
			"EN_call_targdown89",
			"EN_call_targdown90",
			"EN_call_targdown91",
			"EN_call_targdown92",
			"EN_call_targdown93",
			"EN_call_targdown94",
			"EN_call_targdown95",
			"EN_call_targdown96",
			"EN_call_targdown97",
			"EN_call_targdown98",
			"EN_call_targdown99",
			"EN_call_targdown100"
		};
		cover[] = {
			"EN_call_cover01",
			"EN_call_cover02",
			"EN_call_cover03",
			"EN_call_cover04",
			"EN_call_cover05",
			"EN_call_cover06",
			"EN_call_cover07",
			"EN_call_cover08",
			"EN_call_cover09",
			"EN_call_cover10",
			"EN_call_cover11",
			"EN_call_cover12",
			"EN_call_cover13",
			"EN_call_cover14",
			"EN_call_cover15",
			"EN_call_cover16",
			"EN_call_cover17",
			"EN_call_cover18",
			"EN_call_cover19",
			"EN_call_cover20",
			"EN_call_cover21",
			"EN_call_cover22",
			"EN_call_cover23",
			"EN_call_cover24",
			"EN_call_cover25",
			"EN_call_cover26",
			"EN_call_cover27",
			"EN_call_cover28",
			"EN_call_cover29",
			"EN_call_cover30"
		};
		ammoLow[] = {
			"EN_call_ammolow01",
			"EN_call_ammolow02",
			"EN_call_ammolow03",
			"EN_call_ammolow04",
			"EN_call_ammolow05",
			"EN_call_ammolow06",
			"EN_call_ammolow07",
			"EN_call_ammolow08",
			"EN_call_ammolow09",
			"EN_call_ammolow10",
			"EN_call_ammolow11",
			"EN_call_ammolow12",
			"EN_call_ammolow13",
			"EN_call_ammolow14",
			"EN_call_ammolow15",
			"EN_call_ammolow16",
			"EN_call_ammolow17",
			"EN_call_ammolow18",
			"EN_call_ammolow19",
			"EN_call_ammolow20",
			"EN_call_ammolow21",
			"EN_call_ammolow22",
			"EN_call_ammolow23",
			"EN_call_ammolow24",
			"EN_call_ammolow25",
			"EN_call_ammolow26",
			"EN_call_ammolow27",
			"EN_call_ammolow28",
			"EN_call_ammolow29",
			"EN_call_ammolow30"
		};
		reloading[] = {
			"EN_call_reloading01",
			"EN_call_reloading02",
			"EN_call_reloading03",
			"EN_call_reloading04",
			"EN_call_reloading05",
			"EN_call_reloading06",
			"EN_call_reloading07",
			"EN_call_reloading08",
			"EN_call_reloading09",
			"EN_call_reloading10",
			"EN_call_reloading11",
			"EN_call_reloading12",
			"EN_call_reloading13",
			"EN_call_reloading14",
			"EN_call_reloading15",
			"EN_call_reloading16",
			"EN_call_reloading17",
			"EN_call_reloading18",
			"EN_call_reloading19",
			"EN_call_reloading20",
			"EN_call_reloading21",
			"EN_call_reloading22",
			"EN_call_reloading23",
			"EN_call_reloading24",
			"EN_call_reloading25",
			"EN_call_reloading26",
			"EN_call_reloading27",
			"EN_call_reloading28",
			"EN_call_reloading29",
			"EN_call_reloading30",
			"EN_call_reloading31",
			"EN_call_reloading32",
			"EN_call_reloading33",
			"EN_call_reloading34",
			"EN_call_reloading35",
			"EN_call_reloading36",
			"EN_call_reloading37",
			"EN_call_reloading38",
			"EN_call_reloading39",
			"EN_call_reloading40"
		};
		rocketSuppression[] = {
			"EN_warning_rpg01",
			"EN_warning_rpg02",
			"EN_warning_rpg03",
			"EN_warning_rpg04",
			"EN_warning_rpg05",
			"EN_warning_rpg06",
			"EN_warning_rpg07",
			"EN_warning_rpg08",
			"EN_warning_rpg09",
			"EN_warning_rpg10",
			"EN_warning_rpg11",
			"EN_warning_rpg12",
			"EN_warning_rpg13",
			"EN_warning_rpg14",
			"EN_warning_rpg15",
			"EN_warning_rpg16",
			"EN_warning_rpg17",
			"EN_warning_rpg18",
			"EN_warning_rpg19",
			"EN_warning_rpg20",
			"EN_warning_rpg21",
			"EN_warning_rpg22",
			"EN_warning_rpg23",
			"EN_warning_rpg24",
			"EN_warning_rpg25",
			"EN_warning_rpg26",
			"EN_warning_rpg27",
			"EN_warning_rpg28",
			"EN_warning_rpg29",
			"EN_warning_rpg30",
			"EN_warning_rpg31",
			"EN_warning_rpg32",
			"EN_warning_rpg33",
			"EN_warning_rpg34",
			"EN_warning_rpg35",
			"EN_warning_rpg36",
			"EN_warning_rpg37",
			"EN_warning_rpg38",
			"EN_warning_rpg39",
			"EN_warning_rpg40",
			"EN_warning_rpg41",
			"EN_warning_rpg42",
			"EN_warning_rpg43",
			"EN_warning_rpg44",
			"EN_warning_rpg45",
			"EN_warning_rpg46",
			"EN_warning_rpg47",
			"EN_warning_rpg48",
			"EN_warning_rpg49",
			"EN_warning_rpg50",
			"EN_warning_rpg51",
			"EN_warning_rpg52",
			"EN_warning_rpg53",
			"EN_warning_rpg54",
			"EN_warning_rpg55",
			"EN_warning_rpg56",
			"EN_warning_rpg57",
			"EN_warning_rpg58",
			"EN_warning_rpg59",
			"EN_warning_rpg60",
			"EN_warning_rpg61",
			"EN_warning_rpg62",
			"EN_warning_rpg63",
			"EN_warning_rpg64",
			"EN_warning_rpg65",
			"EN_warning_rpg66",
			"EN_warning_rpg67",
			"EN_warning_rpg68",
			"EN_warning_rpg69",
			"EN_warning_rpg70",
			"EN_warning_rpg71",
			"EN_warning_rpg72",
			"EN_warning_rpg73",
			"EN_warning_rpg74",
			"EN_warning_rpg75",
			"EN_warning_rpg76",
			"EN_warning_rpg77",
			"EN_warning_rpg78",
			"EN_warning_rpg79",
			"EN_warning_rpg80",
			"EN_warning_rpg81",
			"EN_warning_rpg82",
			"EN_warning_rpg83",
			"EN_warning_rpg84",
			"EN_warning_rpg85",
			"EN_warning_rpg86",
			"EN_warning_rpg87",
			"EN_warning_rpg88",
			"EN_warning_rpg89",
			"EN_warning_rpg90",
			"EN_warning_rpg91",
			"EN_warning_rpg92",
			"EN_warning_rpg93",
			"EN_warning_rpg94",
			"EN_warning_rpg95",
			"EN_warning_rpg96",
			"EN_warning_rpg97",
			"EN_warning_rpg98",
			"EN_warning_rpg99",
			"EN_warning_rpg100"
		};
		bulletSuppression[] = {
			"EN_warning_suppressed01",
			"EN_warning_suppressed02",
			"EN_warning_suppressed03",
			"EN_warning_suppressed04",
			"EN_warning_suppressed05",
			"EN_warning_suppressed06",
			"EN_warning_suppressed07",
			"EN_warning_suppressed08",
			"EN_warning_suppressed09",
			"EN_warning_suppressed10",
			"EN_warning_suppressed11",
			"EN_warning_suppressed12",
			"EN_warning_suppressed13",
			"EN_warning_suppressed14",
			"EN_warning_suppressed15",
			"EN_warning_suppressed16",
			"EN_warning_suppressed17",
			"EN_warning_suppressed18",
			"EN_warning_suppressed19",
			"EN_warning_suppressed20",
			"EN_warning_suppressed21",
			"EN_warning_suppressed22",
			"EN_warning_suppressed23",
			"EN_warning_suppressed24",
			"EN_warning_suppressed25",
			"EN_warning_suppressed26",
			"EN_warning_suppressed27",
			"EN_warning_suppressed28",
			"EN_warning_suppressed29",
			"EN_warning_suppressed30",
			"EN_warning_suppressed31",
			"EN_warning_suppressed32",
			"EN_warning_suppressed33",
			"EN_warning_suppressed34",
			"EN_warning_suppressed35",
			"EN_warning_suppressed36",
			"EN_warning_suppressed37",
			"EN_warning_suppressed38",
			"EN_warning_suppressed39",
			"EN_warning_suppressed40",
			"EN_warning_suppressed41",
			"EN_warning_suppressed42",
			"EN_warning_suppressed43",
			"EN_warning_suppressed44",
			"EN_warning_suppressed45",
			"EN_warning_suppressed46",
			"EN_warning_suppressed47",
			"EN_warning_suppressed48",
			"EN_warning_suppressed49",
			"EN_warning_suppressed50",
			"EN_warning_suppressed51",
			"EN_warning_suppressed52",
			"EN_warning_suppressed53",
			"EN_warning_suppressed54",
			"EN_warning_suppressed55",
			"EN_warning_suppressed56",
			"EN_warning_suppressed57",
			"EN_warning_suppressed58",
			"EN_warning_suppressed59",
			"EN_warning_suppressed60",
			"EN_warning_suppressed61",
			"EN_warning_suppressed62",
			"EN_warning_suppressed63",
			"EN_warning_suppressed64",
			"EN_warning_suppressed65",
			"EN_warning_suppressed66",
			"EN_warning_suppressed67",
			"EN_warning_suppressed68",
			"EN_warning_suppressed69",
			"EN_warning_suppressed70",
			"EN_warning_suppressed71",
			"EN_warning_suppressed72",
			"EN_warning_suppressed73",
			"EN_warning_suppressed74",
			"EN_warning_suppressed75",
			"EN_warning_suppressed76",
			"EN_warning_suppressed77",
			"EN_warning_suppressed78",
			"EN_warning_suppressed79",
			"EN_warning_suppressed80",
			"EN_warning_suppressed81",
			"EN_warning_suppressed82",
			"EN_warning_suppressed83",
			"EN_warning_suppressed84",
			"EN_warning_suppressed85",
			"EN_warning_suppressed86",
			"EN_warning_suppressed87",
			"EN_warning_suppressed88",
			"EN_warning_suppressed89",
			"EN_warning_suppressed90",
			"EN_warning_suppressed91",
			"EN_warning_suppressed92",
			"EN_warning_suppressed93",
			"EN_warning_suppressed94",
			"EN_warning_suppressed95",
			"EN_warning_suppressed96",
			"EN_warning_suppressed97",
			"EN_warning_suppressed98",
			"EN_warning_suppressed99",
			"EN_warning_suppressed100"
		};
	};
};
